# Generated by Django 6.1 on 2026-08-13 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('ORGANIZACIONAL', 'Organizacional'), ('PERSONAS', 'Personas'), ('FISICO', 'Físico'), ('TECNOLOGICO', 'Tecnológico')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'control Anexo A',
                'verbose_name_plural': 'controles Anexo A',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='AplicabilidadControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aplica', models.BooleanField(default=True)),
                ('justificacion', models.TextField(blank=True, help_text='Justificación de inclusión o exclusión del control.')),
                ('estado_implementacion', models.CharField(choices=[('NO_IMPLEMENTADO', 'No implementado'), ('PARCIAL', 'Parcialmente implementado'), ('IMPLEMENTADO', 'Implementado'), ('NO_APLICA', 'No aplica')], default='NO_IMPLEMENTADO', max_length=20)),
                ('evidencia', models.TextField(blank=True)),
                ('fecha_ultima_revision', models.DateField(blank=True, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_asignados', to=settings.AUTH_USER_MODEL)),
                ('control', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aplicabilidad', to='controles.control')),
            ],
            options={
                'verbose_name': 'declaración de aplicabilidad',
                'verbose_name_plural': 'declaraciones de aplicabilidad (SoA)',
                'ordering': ['control__codigo'],
            },
        ),
    ]
