# Generated by Django 6.1 on 2026-08-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0002_seed_controles_anexo_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplicabilidadcontrol',
            old_name='evidencia',
            new_name='referencia_documento',
        ),
        migrations.AlterField(
            model_name='aplicabilidadcontrol',
            name='referencia_documento',
            field=models.TextField(blank=True, verbose_name='Referencia / Nombre Documento'),
        ),
        migrations.AddField(
            model_name='aplicabilidadcontrol',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='aplicabilidadcontrol',
            name='aplica',
            field=models.BooleanField(default=True, verbose_name='Aplica el control (SI/NO)'),
        ),
        migrations.AlterField(
            model_name='aplicabilidadcontrol',
            name='estado_implementacion',
            field=models.CharField(choices=[('NO_IMPLEMENTADO', 'No implementado'), ('PARCIAL', 'Parcialmente implementado'), ('IMPLEMENTADO', 'Implementado'), ('NO_APLICA', 'No aplica')], default='NO_IMPLEMENTADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='aplicabilidadcontrol',
            name='justificacion',
            field=models.TextField(blank=True, help_text='Justificación de inclusión o exclusión del control.', verbose_name='Justificación del control'),
        ),
    ]
