# Generated by Django 6.1 on 2026-08-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0004_poblar_descripciones_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicabilidadcontrol',
            name='estado_implementacion',
            field=models.CharField(choices=[('NO_IMPLEMENTADO', 'Sin Iniciar'), ('PARCIAL', 'En Proceso'), ('IMPLEMENTADO', 'Implementado')], default='NO_IMPLEMENTADO', max_length=20, verbose_name='Estado'),
        ),
    ]
