# Generated by Django 6.1 on 2026-08-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0005_limitar_opciones_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicabilidadcontrol',
            name='fecha_ultima_revision',
        ),
        migrations.RemoveField(
            model_name='aplicabilidadcontrol',
            name='responsable',
        ),
    ]
