# Generated by Django 6.1 on 2026-08-25 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0006_quitar_responsable_y_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicabilidadcontrol',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, db_column='actualizadoEn'),
        ),
        migrations.AlterField(
            model_name='aplicabilidadcontrol',
            name='control',
            field=models.OneToOneField(db_column='controlId', on_delete=django.db.models.deletion.CASCADE, related_name='aplicabilidad', to='controles.control'),
        ),
        migrations.AlterField(
            model_name='aplicabilidadcontrol',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterField(
            model_name='aplicabilidadcontrol',
            name='estado_implementacion',
            field=models.CharField(choices=[('NO_IMPLEMENTADO', 'Sin Iniciar'), ('PARCIAL', 'En Proceso'), ('IMPLEMENTADO', 'Implementado')], db_column='estadoImplementacion', default='NO_IMPLEMENTADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='aplicabilidadcontrol',
            name='referencia_documento',
            field=models.TextField(blank=True, db_column='referenciaDocumento', verbose_name='Referencia / Nombre Documento'),
        ),
        migrations.AlterModelTable(
            name='aplicabilidadcontrol',
            table='aplicabilidadControl',
        ),
        migrations.AlterModelTable(
            name='control',
            table='control',
        ),
    ]
