# Generated by Django 6.1 on 2026-08-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0007_camel_case_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeralNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('capitulo', models.CharField(blank=True, max_length=100, verbose_name='Capítulo')),
            ],
            options={
                'verbose_name': 'numeral de la norma',
                'verbose_name_plural': 'numerales de la norma',
                'db_table': 'numeralNorma',
                'ordering': ['codigo'],
            },
        ),
    ]
