# Generated by Django 6.1 on 2026-08-14 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('controles', '0002_seed_controles_anexo_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('origen', models.CharField(choices=[('HUMANA_INTENCIONAL', 'Humana intencional'), ('HUMANA_NO_INTENCIONAL', 'Humana no intencional'), ('TECNICA', 'Técnica'), ('AMBIENTAL', 'Ambiental / natural')], max_length=25)),
            ],
            options={
                'verbose_name': 'amenaza',
                'verbose_name_plural': 'amenazas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'vulnerabilidad',
                'verbose_name_plural': 'vulnerabilidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('probabilidad', models.IntegerField(choices=[(1, 'Muy baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy alta')])),
                ('impacto', models.IntegerField(choices=[(1, 'Muy baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy alta')])),
                ('nivel_riesgo', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('estado', models.CharField(choices=[('IDENTIFICADO', 'Identificado'), ('EN_TRATAMIENTO', 'En tratamiento'), ('MITIGADO', 'Mitigado'), ('ACEPTADO', 'Aceptado'), ('CERRADO', 'Cerrado')], default='IDENTIFICADO', max_length=20)),
                ('fecha_identificacion', models.DateField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='activos.activo')),
                ('amenaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riesgos', to='riesgos.amenaza')),
                ('controles', models.ManyToManyField(blank=True, related_name='riesgos', to='controles.control')),
                ('propietario_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riesgos_propios', to=settings.AUTH_USER_MODEL)),
                ('vulnerabilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgos', to='riesgos.vulnerabilidad')),
            ],
            options={
                'verbose_name': 'riesgo',
                'verbose_name_plural': 'riesgos',
                'ordering': ['-nivel_riesgo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='TratamientoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('opcion', models.CharField(choices=[('MITIGAR', 'Mitigar'), ('TRANSFERIR', 'Transferir'), ('EVITAR', 'Evitar'), ('ACEPTAR', 'Aceptar')], max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=15)),
                ('probabilidad_residual', models.IntegerField(blank=True, choices=[(1, 'Muy baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy alta')], null=True)),
                ('impacto_residual', models.IntegerField(blank=True, choices=[(1, 'Muy baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy alta')], null=True)),
                ('nivel_riesgo_residual', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos_asignados', to=settings.AUTH_USER_MODEL)),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='riesgos.riesgo')),
            ],
            options={
                'verbose_name': 'tratamiento de riesgo',
                'verbose_name_plural': 'tratamientos de riesgo',
                'ordering': ['fecha_limite'],
            },
        ),
    ]
