# Generated by Django 6.1 on 2026-08-20 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0007_alter_activo_clase_activo_alter_activo_custodio_and_more'),
        ('riesgos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riesgo',
            name='vulnerabilidad',
        ),
        migrations.AlterModelOptions(
            name='riesgo',
            options={'ordering': ['-riesgo_inherente', 'codigo'], 'verbose_name': 'riesgo', 'verbose_name_plural': 'riesgos'},
        ),
        migrations.RemoveField(
            model_name='riesgo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='riesgo',
            name='nivel_riesgo',
        ),
        migrations.AddField(
            model_name='riesgo',
            name='activos',
            field=models.ManyToManyField(related_name='riesgos', to='activos.activo', verbose_name='Activos afectados'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='esta_activo',
            field=models.BooleanField(default=True, verbose_name='¿Riesgo activo?'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='riesgo_inherente',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Riesgo inherente'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='impacto',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Impacto (1-10)'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='probabilidad',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Probabilidad (1-10)'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='impacto_residual',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='probabilidad_residual',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.DeleteModel(
            name='Vulnerabilidad',
        ),
    ]
