# Generated by Django 6.1 on 2026-08-21 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0002_remove_riesgo_vulnerabilidad_alter_riesgo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riesgo',
            name='impacto',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Impacto (1-20)'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='probabilidad',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Probabilidad (1-5)'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='impacto_residual',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='probabilidad_residual',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
