# Generated by Django 6.1 on 2026-08-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0003_alter_riesgo_impacto_alter_riesgo_probabilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riesgo',
            name='impacto',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Insignificante'), (5, 'Menor'), (10, 'Moderado'), (15, 'Mayor'), (20, 'Catastrófico')], verbose_name='Impacto'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='probabilidad',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muy Rara'), (2, 'Improbable'), (3, 'Posible'), (4, 'Probable'), (5, 'Casi Seguro')], verbose_name='Probabilidad'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='impacto_residual',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Insignificante'), (5, 'Menor'), (10, 'Moderado'), (15, 'Mayor'), (20, 'Catastrófico')], null=True),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='probabilidad_residual',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Muy Rara'), (2, 'Improbable'), (3, 'Posible'), (4, 'Probable'), (5, 'Casi Seguro')], null=True),
        ),
    ]
