# Generated by Django 6.1 on 2026-08-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0004_alter_riesgo_impacto_alter_riesgo_probabilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riesgo',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Justificación'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='estado',
            field=models.CharField(choices=[('IDENTIFICADO', 'Identificado'), ('EN_TRATAMIENTO', 'En tratamiento'), ('MITIGADO', 'Mitigado'), ('ACEPTADO', 'Aceptado'), ('CERRADO', 'Cerrado')], default='IDENTIFICADO', max_length=20, verbose_name='Opción de tratamiento'),
        ),
    ]
