# Generated by Django 6.1 on 2026-08-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0005_alter_riesgo_descripcion_alter_riesgo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riesgo',
            name='estado',
        ),
    ]
