# Generated by Django 6.1 on 2026-08-21 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0006_remove_riesgo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientoriesgo',
            name='accion_mitigacion',
            field=models.TextField(blank=True, verbose_name='Acción de mitigación'),
        ),
        migrations.AddField(
            model_name='tratamientoriesgo',
            name='evidencias_esperadas',
            field=models.TextField(blank=True, verbose_name='Evidencias esperadas'),
        ),
        migrations.AddField(
            model_name='tratamientoriesgo',
            name='recursos_necesarios',
            field=models.TextField(blank=True, verbose_name='Recursos necesarios'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cierre (plazo)'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='opcion',
            field=models.CharField(choices=[('MITIGAR', 'Mitigar'), ('TRANSFERIR', 'Transferir'), ('EVITAR', 'Evitar'), ('ACEPTAR', 'Aceptar')], max_length=15, verbose_name='Opción de tratamiento'),
        ),
        migrations.CreateModel(
            name='ArchivoAdjuntoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='riesgos/tratamientos/%Y/%m/', verbose_name='Archivo')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='riesgos.tratamientoriesgo')),
            ],
            options={
                'verbose_name': 'archivo adjunto',
                'verbose_name_plural': 'archivos adjuntos',
                'ordering': ['-subido_en'],
            },
        ),
    ]
