# Generated by Django 6.1 on 2026-08-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0007_tratamientoriesgo_accion_mitigacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientoriesgo',
            name='fecha_proximo_seguimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de próximo seguimiento'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de seguimiento'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite (plazo)'),
        ),
    ]
