# Generated by Django 6.1 on 2026-08-24 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0008_tratamientoriesgo_fecha_proximo_seguimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='riesgo',
            name='propietario_riesgo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='riesgos_propios', to=settings.AUTH_USER_MODEL, verbose_name='Propietario del riesgo'),
        ),
    ]
