# Generated by Django 6.1 on 2026-08-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0009_alter_riesgo_propietario_riesgo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riesgo',
            options={'ordering': ['codigo'], 'verbose_name': 'riesgo', 'verbose_name_plural': 'riesgos'},
        ),
        migrations.RenameField(
            model_name='tratamientoriesgo',
            old_name='nivel_riesgo_residual',
            new_name='riesgo_residual',
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='riesgo_residual',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Riesgo residual'),
        ),
    ]
