# Generated by Django 6.1 on 2026-08-25 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_camel_case_db'),
        ('controles', '0007_camel_case_db'),
        ('riesgos', '0010_rename_nivel_riesgo_residual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenaza',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, db_column='actualizadoEn'),
        ),
        migrations.AlterField(
            model_name='amenaza',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterField(
            model_name='archivoadjuntotratamiento',
            name='subido_en',
            field=models.DateTimeField(auto_now_add=True, db_column='subidoEn'),
        ),
        migrations.AlterField(
            model_name='archivoadjuntotratamiento',
            name='tratamiento',
            field=models.ForeignKey(db_column='tratamientoId', on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='riesgos.tratamientoriesgo'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='activos',
            field=models.ManyToManyField(db_table='riesgoActivos', related_name='riesgos', to='activos.activo', verbose_name='Activos afectados'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, db_column='actualizadoEn'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='amenaza',
            field=models.ForeignKey(db_column='amenazaId', on_delete=django.db.models.deletion.PROTECT, related_name='riesgos', to='riesgos.amenaza'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='controles',
            field=models.ManyToManyField(blank=True, db_table='riesgoControles', related_name='riesgos', to='controles.control'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='esta_activo',
            field=models.BooleanField(db_column='estaActivo', default=True, verbose_name='¿Riesgo activo?'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='fecha_identificacion',
            field=models.DateField(auto_now_add=True, db_column='fechaIdentificacion'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='propietario_riesgo',
            field=models.ForeignKey(blank=True, db_column='propietarioRiesgoId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='riesgos_propios', to=settings.AUTH_USER_MODEL, verbose_name='Propietario del riesgo'),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='riesgo_inherente',
            field=models.PositiveSmallIntegerField(db_column='riesgoInherente', default=0, editable=False, verbose_name='Riesgo inherente'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='accion_mitigacion',
            field=models.TextField(blank=True, db_column='accionMitigacion', verbose_name='Acción de mitigación'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, db_column='actualizadoEn'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='evidencias_esperadas',
            field=models.TextField(blank=True, db_column='evidenciasEsperadas', verbose_name='Evidencias esperadas'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='fecha_cierre',
            field=models.DateField(blank=True, db_column='fechaCierre', null=True, verbose_name='Fecha de seguimiento'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='fecha_limite',
            field=models.DateField(blank=True, db_column='fechaLimite', null=True, verbose_name='Fecha límite (plazo)'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='fecha_proximo_seguimiento',
            field=models.DateField(blank=True, db_column='fechaProximoSeguimiento', null=True, verbose_name='Fecha de próximo seguimiento'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='impacto_residual',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Insignificante'), (5, 'Menor'), (10, 'Moderado'), (15, 'Mayor'), (20, 'Catastrófico')], db_column='impactoResidual', null=True),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='probabilidad_residual',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Muy Rara'), (2, 'Improbable'), (3, 'Posible'), (4, 'Probable'), (5, 'Casi Seguro')], db_column='probabilidadResidual', null=True),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='recursos_necesarios',
            field=models.TextField(blank=True, db_column='recursosNecesarios', verbose_name='Recursos necesarios'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='responsable',
            field=models.ForeignKey(db_column='responsableId', on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='riesgo',
            field=models.ForeignKey(db_column='riesgoId', on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='riesgos.riesgo'),
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='riesgo_residual',
            field=models.PositiveSmallIntegerField(blank=True, db_column='riesgoResidual', editable=False, null=True, verbose_name='Riesgo residual'),
        ),
        migrations.AlterModelTable(
            name='amenaza',
            table='amenaza',
        ),
        migrations.AlterModelTable(
            name='archivoadjuntotratamiento',
            table='archivoAdjuntoTratamiento',
        ),
        migrations.AlterModelTable(
            name='riesgo',
            table='riesgo',
        ),
        migrations.AlterModelTable(
            name='tratamientoriesgo',
            table='tratamientoRiesgo',
        ),
    ]
