# Generated by Django 6.1 on 2026-08-26 20:41

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0011_camel_case_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjuntotratamiento',
            name='archivo',
            field=models.FileField(upload_to='riesgos/tratamientos/%Y/%m/', validators=[apps.core.validators.validar_extension_archivo, apps.core.validators.validar_tamano_archivo], verbose_name='Archivo'),
        ),
    ]
