# Generated by Django 6.1 on 2026-08-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0012_alter_archivoadjuntotratamiento_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamientoriesgo',
            name='estado',
        ),
    ]
