# Generated by Django 6.1 on 2026-08-28 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0013_remove_tratamientoriesgo_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riesgo',
            name='propietarios_riesgo',
            field=models.ManyToManyField(blank=True, db_table='riesgoPropietarios', related_name='riesgos_propios_m2m', to=settings.AUTH_USER_MODEL, verbose_name='Propietarios del riesgo'),
        ),
    ]
