# Generated by Django 6.1 on 2026-08-28 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0015_copiar_propietario_a_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riesgo',
            name='propietario_riesgo',
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='propietarios_riesgo',
            field=models.ManyToManyField(blank=True, db_table='riesgoPropietarios', related_name='riesgos_propios', to=settings.AUTH_USER_MODEL, verbose_name='Propietarios del riesgo'),
        ),
    ]
