# Generated by Django 6.1 on 2026-08-28 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0016_remove_riesgo_propietario_riesgo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientoriesgo',
            name='responsables',
            field=models.ManyToManyField(blank=True, db_table='tratamientoRiesgoResponsables', related_name='tratamientos_asignados_m2m', to=settings.AUTH_USER_MODEL, verbose_name='Responsables'),
        ),
    ]
