# Generated by Django 6.1 on 2026-08-28 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0018_copiar_responsable_a_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamientoriesgo',
            name='responsable',
        ),
        migrations.AlterField(
            model_name='tratamientoriesgo',
            name='responsables',
            field=models.ManyToManyField(blank=True, db_table='tratamientoRiesgoResponsables', related_name='tratamientos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Responsables'),
        ),
    ]
