# Generated by Django 6.1 on 2026-08-28 20:18

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0019_remove_tratamientoriesgo_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjuntotratamiento',
            name='archivo',
            field=models.FileField(max_length=255, upload_to='riesgos/tratamientos/%Y/%m/', validators=[apps.core.validators.validar_extension_archivo, apps.core.validators.validar_tamano_archivo], verbose_name='Archivo'),
        ),
    ]
