# Generated by Django 6.1 on 2026-09-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0021_alter_archivoadjuntotratamiento_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamientoriesgo',
            name='descripcion',
        ),
    ]
