# Generated by Django 6.1 on 2026-08-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0008_camel_case_db'),
        ('indicadores', '0005_camel_case_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
                ('componente_politica', models.TextField(blank=True, db_column='componentePolitica', verbose_name='Componente de la política al cual contribuye')),
                ('responsables_seguimiento', models.TextField(blank=True, db_column='responsablesSeguimiento', verbose_name='Responsables de seguimiento')),
                ('indicador_desempeno', models.TextField(blank=True, db_column='indicadorDesempeno', verbose_name='Indicador de desempeño')),
                ('meta_indicador', models.TextField(blank=True, db_column='metaIndicador', verbose_name='Meta del indicador')),
                ('indicadores', models.ManyToManyField(blank=True, db_table='objetivoIndicadores', related_name='objetivos', to='indicadores.indicador', verbose_name='Indicadores relacionados')),
                ('procesos_asociados', models.ManyToManyField(blank=True, db_table='objetivoProcesos', related_name='objetivos', to='activos.proceso', verbose_name='Procesos asociados')),
            ],
            options={
                'verbose_name': 'objetivo',
                'verbose_name_plural': 'objetivos',
                'db_table': 'objetivo',
                'ordering': ['id'],
            },
        ),
    ]
