# Generated by Django 6.1 on 2026-08-26 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('actividad', models.TextField(verbose_name='Actividad')),
                ('responsables', models.TextField(blank=True, verbose_name='Responsables')),
                ('recursos', models.TextField(blank=True, verbose_name='Recursos')),
                ('periodo', models.CharField(blank=True, max_length=100, verbose_name='Periodo')),
                ('plazo', models.DateField(blank=True, null=True, verbose_name='Plazo')),
                ('estado_ejecucion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada'), ('VENCIDA', 'Vencida')], db_column='estadoEjecucion', default='PENDIENTE', max_length=15, verbose_name='Estado de ejecución')),
                ('objetivo', models.ForeignKey(db_column='objetivoId', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='objetivos.objetivo', verbose_name='Objetivo')),
            ],
            options={
                'verbose_name': 'actividad de objetivo',
                'verbose_name_plural': 'actividades de objetivos',
                'db_table': 'actividadObjetivo',
                'ordering': ['objetivo', 'plazo'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjuntoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='objetivos/actividades/%Y/%m/', verbose_name='Archivo')),
                ('subido_en', models.DateTimeField(auto_now_add=True, db_column='subidoEn')),
                ('actividad', models.ForeignKey(db_column='actividadId', on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='objetivos.actividadobjetivo')),
            ],
            options={
                'verbose_name': 'archivo adjunto',
                'verbose_name_plural': 'archivos adjuntos',
                'db_table': 'archivoAdjuntoActividad',
                'ordering': ['-subido_en'],
            },
        ),
    ]
