# Generated by Django 6.1 on 2026-08-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0002_actividadobjetivo_archivoadjuntoactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadobjetivo',
            name='periodo',
            field=models.CharField(blank=True, choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=15, verbose_name='Periodo'),
        ),
    ]
