# Generated by Django 6.1 on 2026-08-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0003_alter_actividadobjetivo_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadobjetivo',
            name='estado_ejecucion',
        ),
    ]
