# Generated by Django 6.1 on 2026-08-26 20:41

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0004_remove_actividadobjetivo_estado_ejecucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjuntoactividad',
            name='archivo',
            field=models.FileField(upload_to='objetivos/actividades/%Y/%m/', validators=[apps.core.validators.validar_extension_archivo, apps.core.validators.validar_tamano_archivo], verbose_name='Archivo'),
        ),
    ]
