# Generated by Django 6.1 on 2026-08-28 21:03

import apps.core.validators
import apps.objetivos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0006_alter_archivoadjuntoactividad_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjuntoactividad',
            name='archivo',
            field=models.FileField(max_length=255, upload_to=apps.objetivos.models.ruta_soporte_actividad, validators=[apps.core.validators.validar_extension_archivo, apps.core.validators.validar_tamano_archivo], verbose_name='Archivo'),
        ),
    ]
