# Generated by Django 6.1 on 2026-09-04 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionPersonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('fecha_revision', models.DateField(db_column='fechaRevision', verbose_name='Fecha de revisión')),
                ('muestra_seleccionada', models.CharField(blank=True, db_column='muestraSeleccionada', max_length=300, verbose_name='Muestra seleccionada')),
                ('responsable_talento_humano', models.ForeignKey(db_column='responsableTalentoHumanoId', on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_personas_como_talento_humano', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Talento Humano')),
                ('responsable_tecnologia', models.ForeignKey(db_column='responsableTecnologiaId', on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_personas_como_tecnologia', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Tecnología')),
                ('revisor', models.ForeignKey(db_column='revisorId', on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_personas_como_revisor', to=settings.AUTH_USER_MODEL, verbose_name='Revisor / Oficial de Seguridad')),
            ],
            options={
                'verbose_name': 'revisión de controles de personas',
                'verbose_name_plural': 'revisiones de controles de personas',
                'db_table': 'revisionPersonas',
                'ordering': ['-fecha_revision'],
            },
        ),
    ]
