# Generated by Django 6.1 on 2026-09-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaChecklistPersonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_codigo', models.CharField(db_column='controlCodigo', max_length=10, verbose_name='Control')),
                ('control_nombre', models.CharField(db_column='controlNombre', max_length=200, verbose_name='Nombre del control')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='N.')),
                ('texto', models.TextField(verbose_name='Pregunta / criterio')),
            ],
            options={
                'verbose_name': 'pregunta de checklist (Personas)',
                'verbose_name_plural': 'preguntas de checklist (Personas)',
                'db_table': 'preguntaChecklistPersonas',
                'ordering': ['control_codigo', 'numero'],
                'unique_together': {('control_codigo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaChecklistPersonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('resultado', models.CharField(blank=True, choices=[('C', 'C - Cumple'), ('CP', 'CP - Cumple parcialmente'), ('NC', 'NC - No cumple'), ('NE', 'NE - No evidenciado')], max_length=2, verbose_name='Resultado (C / CP / NC / NE)')),
                ('evidencia', models.TextField(blank=True, verbose_name='Evidencia / observación')),
                ('pregunta', models.ForeignKey(db_column='preguntaId', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='revisiones.preguntachecklistpersonas')),
                ('revision', models.ForeignKey(db_column='revisionId', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_checklist', to='revisiones.revisionpersonas')),
            ],
            options={
                'verbose_name': 'respuesta de checklist (Personas)',
                'verbose_name_plural': 'respuestas de checklist (Personas)',
                'db_table': 'respuestaChecklistPersonas',
                'ordering': ['pregunta__control_codigo', 'pregunta__numero'],
                'unique_together': {('revision', 'pregunta')},
            },
        ),
    ]
