# Generated by Django 6.1 on 2026-09-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisiones', '0003_seed_preguntas_a61'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionpersonas',
            name='finalizada',
            field=models.BooleanField(db_column='finalizada', default=False, help_text='Una vez finalizada, el checklist queda de solo lectura salvo para administradores.', verbose_name='Finalizada'),
        ),
    ]
