# Generated by Django 6.1 on 2026-09-21 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisiones', '0011_seed_preguntas_a68'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaChecklistFisicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_codigo', models.CharField(db_column='controlCodigo', max_length=10, verbose_name='Control')),
                ('control_nombre', models.CharField(db_column='controlNombre', max_length=200, verbose_name='Nombre del control')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='N.')),
                ('texto', models.TextField(verbose_name='Pregunta / criterio')),
            ],
            options={
                'verbose_name': 'pregunta de checklist (Físicos)',
                'verbose_name_plural': 'preguntas de checklist (Físicos)',
                'db_table': 'preguntaChecklistFisicos',
                'ordering': ['control_codigo', 'numero'],
                'unique_together': {('control_codigo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='PreguntaChecklistOrganizacionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_codigo', models.CharField(db_column='controlCodigo', max_length=10, verbose_name='Control')),
                ('control_nombre', models.CharField(db_column='controlNombre', max_length=200, verbose_name='Nombre del control')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='N.')),
                ('texto', models.TextField(verbose_name='Pregunta / criterio')),
            ],
            options={
                'verbose_name': 'pregunta de checklist (Organizacionales)',
                'verbose_name_plural': 'preguntas de checklist (Organizacionales)',
                'db_table': 'preguntaChecklistOrganizacionales',
                'ordering': ['control_codigo', 'numero'],
                'unique_together': {('control_codigo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='PreguntaChecklistTecnologicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_codigo', models.CharField(db_column='controlCodigo', max_length=10, verbose_name='Control')),
                ('control_nombre', models.CharField(db_column='controlNombre', max_length=200, verbose_name='Nombre del control')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='N.')),
                ('texto', models.TextField(verbose_name='Pregunta / criterio')),
            ],
            options={
                'verbose_name': 'pregunta de checklist (Tecnológicos)',
                'verbose_name_plural': 'preguntas de checklist (Tecnológicos)',
                'db_table': 'preguntaChecklistTecnologicos',
                'ordering': ['control_codigo', 'numero'],
                'unique_together': {('control_codigo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='RevisionFisicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('fecha_revision', models.DateField(db_column='fechaRevision', verbose_name='Fecha de revisión')),
                ('muestra_seleccionada', models.CharField(blank=True, db_column='muestraSeleccionada', max_length=300, verbose_name='Muestra seleccionada')),
                ('finalizada', models.BooleanField(db_column='finalizada', default=False, help_text='Una vez finalizada, el checklist queda de solo lectura salvo para administradores.', verbose_name='Finalizada')),
                ('responsable', models.ForeignKey(db_column='responsableId', on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_fisicos_como_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Infraestructura y Recursos Físicos')),
                ('revisor', models.ForeignKey(db_column='revisorId', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_como_revisor', to=settings.AUTH_USER_MODEL, verbose_name='Revisor / Oficial de Seguridad')),
            ],
            options={
                'verbose_name': 'revisión de controles físicos',
                'verbose_name_plural': 'revisiones de controles físicos',
                'db_table': 'revisionFisicos',
                'ordering': ['-fecha_revision'],
            },
        ),
        migrations.CreateModel(
            name='RevisionOrganizacionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('fecha_revision', models.DateField(db_column='fechaRevision', verbose_name='Fecha de revisión')),
                ('muestra_seleccionada', models.CharField(blank=True, db_column='muestraSeleccionada', max_length=300, verbose_name='Muestra seleccionada')),
                ('finalizada', models.BooleanField(db_column='finalizada', default=False, help_text='Una vez finalizada, el checklist queda de solo lectura salvo para administradores.', verbose_name='Finalizada')),
                ('responsable', models.ForeignKey(db_column='responsableId', on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_organizacionales_como_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Gestión de Procesos')),
                ('revisor', models.ForeignKey(db_column='revisorId', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_como_revisor', to=settings.AUTH_USER_MODEL, verbose_name='Revisor / Oficial de Seguridad')),
            ],
            options={
                'verbose_name': 'revisión de controles organizacionales',
                'verbose_name_plural': 'revisiones de controles organizacionales',
                'db_table': 'revisionOrganizacionales',
                'ordering': ['-fecha_revision'],
            },
        ),
        migrations.CreateModel(
            name='RevisionTecnologicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('fecha_revision', models.DateField(db_column='fechaRevision', verbose_name='Fecha de revisión')),
                ('muestra_seleccionada', models.CharField(blank=True, db_column='muestraSeleccionada', max_length=300, verbose_name='Muestra seleccionada')),
                ('finalizada', models.BooleanField(db_column='finalizada', default=False, help_text='Una vez finalizada, el checklist queda de solo lectura salvo para administradores.', verbose_name='Finalizada')),
                ('responsable', models.ForeignKey(db_column='responsableId', on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_tecnologicos_como_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Tecnología')),
                ('revisor', models.ForeignKey(db_column='revisorId', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_como_revisor', to=settings.AUTH_USER_MODEL, verbose_name='Revisor / Oficial de Seguridad')),
            ],
            options={
                'verbose_name': 'revisión de controles tecnológicos',
                'verbose_name_plural': 'revisiones de controles tecnológicos',
                'db_table': 'revisionTecnologicos',
                'ordering': ['-fecha_revision'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaChecklistFisicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('resultado', models.CharField(blank=True, choices=[('C', 'C - Cumple'), ('CP', 'CP - Cumple parcialmente'), ('NC', 'NC - No cumple'), ('NE', 'NE - No evidenciado')], max_length=2, verbose_name='Resultado (C / CP / NC / NE)')),
                ('evidencia', models.TextField(blank=True, verbose_name='Evidencia / observación')),
                ('pregunta', models.ForeignKey(db_column='preguntaId', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='revisiones.preguntachecklistfisicos')),
                ('revision', models.ForeignKey(db_column='revisionId', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_checklist', to='revisiones.revisionfisicos')),
            ],
            options={
                'verbose_name': 'respuesta de checklist (Físicos)',
                'verbose_name_plural': 'respuestas de checklist (Físicos)',
                'db_table': 'respuestaChecklistFisicos',
                'ordering': ['pregunta__control_codigo', 'pregunta__numero'],
                'unique_together': {('revision', 'pregunta')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaChecklistOrganizacionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('resultado', models.CharField(blank=True, choices=[('C', 'C - Cumple'), ('CP', 'CP - Cumple parcialmente'), ('NC', 'NC - No cumple'), ('NE', 'NE - No evidenciado')], max_length=2, verbose_name='Resultado (C / CP / NC / NE)')),
                ('evidencia', models.TextField(blank=True, verbose_name='Evidencia / observación')),
                ('pregunta', models.ForeignKey(db_column='preguntaId', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='revisiones.preguntachecklistorganizacionales')),
                ('revision', models.ForeignKey(db_column='revisionId', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_checklist', to='revisiones.revisionorganizacionales')),
            ],
            options={
                'verbose_name': 'respuesta de checklist (Organizacionales)',
                'verbose_name_plural': 'respuestas de checklist (Organizacionales)',
                'db_table': 'respuestaChecklistOrganizacionales',
                'ordering': ['pregunta__control_codigo', 'pregunta__numero'],
                'unique_together': {('revision', 'pregunta')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaChecklistTecnologicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('resultado', models.CharField(blank=True, choices=[('C', 'C - Cumple'), ('CP', 'CP - Cumple parcialmente'), ('NC', 'NC - No cumple'), ('NE', 'NE - No evidenciado')], max_length=2, verbose_name='Resultado (C / CP / NC / NE)')),
                ('evidencia', models.TextField(blank=True, verbose_name='Evidencia / observación')),
                ('pregunta', models.ForeignKey(db_column='preguntaId', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='revisiones.preguntachecklisttecnologicos')),
                ('revision', models.ForeignKey(db_column='revisionId', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_checklist', to='revisiones.revisiontecnologicos')),
            ],
            options={
                'verbose_name': 'respuesta de checklist (Tecnológicos)',
                'verbose_name_plural': 'respuestas de checklist (Tecnológicos)',
                'db_table': 'respuestaChecklistTecnologicos',
                'ordering': ['pregunta__control_codigo', 'pregunta__numero'],
                'unique_together': {('revision', 'pregunta')},
            },
        ),
    ]
