# Generated by Django 6.1 on 2026-09-21 16:29

from django.db import migrations, models


def backfill_control_orden(apps, schema_editor):
    """Calcula control_orden (el número tras el último punto de control_codigo) para las
    preguntas ya insertadas por las migraciones de seed 0013-0015, ya que el default=0
    del AddField no refleja el valor real y save() solo se ejecuta en escrituras futuras."""
    for nombre_modelo in ['PreguntaChecklistOrganizacionales', 'PreguntaChecklistFisicos', 'PreguntaChecklistTecnologicos']:
        Pregunta = apps.get_model('revisiones', nombre_modelo)
        for pregunta in Pregunta.objects.all():
            numero_control = pregunta.control_codigo.rsplit('.', 1)[-1]
            if numero_control.isdigit():
                pregunta.control_orden = int(numero_control)
                pregunta.save(update_fields=['control_orden'])


def revertir(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('revisiones', '0015_seed_preguntas_tecnologicos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntachecklistfisicos',
            options={'ordering': ['control_orden', 'numero'], 'verbose_name': 'pregunta de checklist (Físicos)', 'verbose_name_plural': 'preguntas de checklist (Físicos)'},
        ),
        migrations.AlterModelOptions(
            name='preguntachecklistorganizacionales',
            options={'ordering': ['control_orden', 'numero'], 'verbose_name': 'pregunta de checklist (Organizacionales)', 'verbose_name_plural': 'preguntas de checklist (Organizacionales)'},
        ),
        migrations.AlterModelOptions(
            name='preguntachecklisttecnologicos',
            options={'ordering': ['control_orden', 'numero'], 'verbose_name': 'pregunta de checklist (Tecnológicos)', 'verbose_name_plural': 'preguntas de checklist (Tecnológicos)'},
        ),
        migrations.AlterModelOptions(
            name='respuestachecklistfisicos',
            options={'ordering': ['pregunta__control_orden', 'pregunta__numero'], 'verbose_name': 'respuesta de checklist (Físicos)', 'verbose_name_plural': 'respuestas de checklist (Físicos)'},
        ),
        migrations.AlterModelOptions(
            name='respuestachecklistorganizacionales',
            options={'ordering': ['pregunta__control_orden', 'pregunta__numero'], 'verbose_name': 'respuesta de checklist (Organizacionales)', 'verbose_name_plural': 'respuestas de checklist (Organizacionales)'},
        ),
        migrations.AlterModelOptions(
            name='respuestachecklisttecnologicos',
            options={'ordering': ['pregunta__control_orden', 'pregunta__numero'], 'verbose_name': 'respuesta de checklist (Tecnológicos)', 'verbose_name_plural': 'respuestas de checklist (Tecnológicos)'},
        ),
        migrations.AddField(
            model_name='preguntachecklistfisicos',
            name='control_orden',
            field=models.PositiveSmallIntegerField(db_column='controlOrden', default=0, editable=False),
        ),
        migrations.AddField(
            model_name='preguntachecklistorganizacionales',
            name='control_orden',
            field=models.PositiveSmallIntegerField(db_column='controlOrden', default=0, editable=False),
        ),
        migrations.AddField(
            model_name='preguntachecklisttecnologicos',
            name='control_orden',
            field=models.PositiveSmallIntegerField(db_column='controlOrden', default=0, editable=False),
        ),
        migrations.RunPython(backfill_control_orden, revertir),
    ]
