# Generated by Django 6.1 on 2026-09-22 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisiones', '0016_alter_preguntachecklistfisicos_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('periodo', models.CharField(help_text='Ej. "2026-S2" o "2026".', max_length=30, verbose_name='Periodo')),
                ('fecha_revision', models.DateField(db_column='fechaRevision', verbose_name='Fecha de revisión')),
                ('lugar_modalidad', models.CharField(blank=True, db_column='lugarModalidad', max_length=150, verbose_name='Lugar / modalidad')),
                ('estado_acciones_previas', models.TextField(blank=True, db_column='estadoAccionesPrevias', verbose_name='a) Estado de las acciones de revisiones por la dirección previas')),
                ('cambios_cuestiones_externas_internas', models.TextField(blank=True, db_column='cambiosCuestionesExternasInternas', verbose_name='b) Cambios en las cuestiones externas e internas pertinentes al SGSI')),
                ('cambios_partes_interesadas', models.TextField(blank=True, db_column='cambiosPartesInteresadas', verbose_name='c) Cambios en las necesidades y expectativas de las partes interesadas')),
                ('desempeno_no_conformidades', models.TextField(blank=True, db_column='desempenoNoConformidades', verbose_name='d.1) No conformidades y acciones correctivas')),
                ('desempeno_seguimiento_medicion', models.TextField(blank=True, db_column='desempenoSeguimientoMedicion', verbose_name='d.2) Resultados de seguimiento y medición (indicadores)')),
                ('desempeno_auditorias', models.TextField(blank=True, db_column='desempenoAuditorias', verbose_name='d.3) Resultados de auditoría')),
                ('desempeno_objetivos', models.TextField(blank=True, db_column='desempenoObjetivos', verbose_name='d.4) Cumplimiento de los objetivos de seguridad de la información')),
                ('retroalimentacion_partes_interesadas', models.TextField(blank=True, db_column='retroalimentacionPartesInteresadas', verbose_name='e) Retroalimentación de las partes interesadas')),
                ('resultados_riesgos', models.TextField(blank=True, db_column='resultadosRiesgos', verbose_name='f) Resultados de la valoración de riesgos y estado del plan de tratamiento')),
                ('oportunidades_mejora', models.TextField(blank=True, db_column='oportunidadesMejora', verbose_name='g) Oportunidades de mejora continua')),
                ('conclusiones_generales', models.TextField(blank=True, db_column='conclusionesGenerales', verbose_name='Conclusiones generales')),
                ('finalizada', models.BooleanField(default=False, help_text='Una vez finalizada, el acta queda de solo lectura salvo para administradores.', verbose_name='Finalizada')),
                ('asistentes', models.ManyToManyField(blank=True, db_table='revisionDireccionAsistentes', related_name='revisiones_direccion_asistidas', to=settings.AUTH_USER_MODEL, verbose_name='Asistentes')),
                ('preside', models.ForeignKey(db_column='presideId', on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_direccion_presididas', to=settings.AUTH_USER_MODEL, verbose_name='Preside la revisión (Alta Dirección)')),
            ],
            options={
                'verbose_name': 'revisión por la dirección',
                'verbose_name_plural': 'revisiones por la dirección',
                'db_table': 'revisionDireccion',
                'ordering': ['-fecha_revision'],
            },
        ),
        migrations.CreateModel(
            name='CompromisoRevisionDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('descripcion', models.TextField(verbose_name='Compromiso / decisión')),
                ('fecha_limite', models.DateField(blank=True, db_column='fechaLimite', null=True, verbose_name='Fecha límite')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=15)),
                ('observaciones_cierre', models.TextField(blank=True, db_column='observacionesCierre', verbose_name='Observaciones de cierre')),
                ('responsable', models.ForeignKey(db_column='responsableId', on_delete=django.db.models.deletion.PROTECT, related_name='compromisos_revision_direccion', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('revision', models.ForeignKey(db_column='revisionId', on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='revisiones.revisiondireccion')),
            ],
            options={
                'verbose_name': 'compromiso de revisión por la dirección',
                'verbose_name_plural': 'compromisos de revisión por la dirección',
                'db_table': 'compromisoRevisionDireccion',
                'ordering': ['fecha_limite', 'id'],
            },
        ),
    ]
