# Generated by Django 6.1 on 2026-09-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_empleados_desde_usuarios'),
        ('revisiones', '0017_revisiondireccion_compromisorevisiondireccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisorevisiondireccion',
            name='responsable',
            field=models.ForeignKey(db_column='responsableId', on_delete=django.db.models.deletion.PROTECT, related_name='compromisos_revision_direccion', to='accounts.empleado', verbose_name='Responsable'),
        ),
        migrations.RemoveField(
            model_name='revisiondireccion',
            name='asistentes',
        ),
        migrations.AlterField(
            model_name='revisiondireccion',
            name='preside',
            field=models.ForeignKey(db_column='presideId', on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_direccion_presididas', to='accounts.empleado', verbose_name='Preside la revisión (Alta Dirección)'),
        ),
        migrations.AddField(
            model_name='revisiondireccion',
            name='asistentes',
            field=models.ManyToManyField(blank=True, db_table='revisionDireccionAsistentes', related_name='revisiones_direccion_asistidas', to='accounts.empleado', verbose_name='Asistentes'),
        ),
    ]
