# Generated by Django 6.1 on 2026-09-04 13:25

import apps.core.validators
import apps.incidentes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='No.')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('nombre_evento', models.CharField(db_column='nombreEvento', max_length=200, verbose_name='Nombre del evento o incidente')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('EVENTO', 'Evento'), ('INCIDENTE', 'Incidente')], max_length=15, verbose_name='Tipo')),
                ('fuente', models.CharField(blank=True, max_length=200, verbose_name='Fuente')),
                ('registrado_por', models.ForeignKey(db_column='registradoPorId', on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registro por')),
                ('responsable', models.ForeignKey(db_column='responsableId', on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'incidente/evento de seguridad',
                'verbose_name_plural': 'matriz de incidentes y eventos de seguridad',
                'db_table': 'incidente',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjuntoIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=255, upload_to=apps.incidentes.models.ruta_soporte_incidente, validators=[apps.core.validators.validar_extension_archivo, apps.core.validators.validar_tamano_archivo], verbose_name='Archivo')),
                ('subido_en', models.DateTimeField(auto_now_add=True, db_column='subidoEn')),
                ('incidente', models.ForeignKey(db_column='incidenteId', on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='incidentes.incidente')),
            ],
            options={
                'verbose_name': 'soporte de incidente',
                'verbose_name_plural': 'soportes de incidente',
                'db_table': 'archivoAdjuntoIncidente',
                'ordering': ['-subido_en'],
            },
        ),
    ]
