# Generated by Django 6.1 on 2026-08-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0008_camel_case_db'),
        ('controles', '0007_camel_case_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'tipo de hallazgo',
                'verbose_name_plural': 'tipos de hallazgo',
                'db_table': 'tipoHallazgo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('fecha_deteccion', models.DateField(db_column='fechaDeteccion', verbose_name='Fecha de detección')),
                ('descripcion', models.TextField(verbose_name='Descripción de la no conformidad / hallazgo')),
                ('evidencia_asociada', models.TextField(blank=True, db_column='evidenciaAsociada', verbose_name='Evidencia asociada')),
                ('analisis_causa', models.TextField(blank=True, db_column='analisisCausa', verbose_name='Análisis de causa (5 Porqués / Ishikawa)')),
                ('accion_correctiva', models.TextField(blank=True, db_column='accionCorrectiva', verbose_name='Acción correctiva')),
                ('responsable', models.CharField(blank=True, max_length=250, verbose_name='Responsable')),
                ('fecha_compromiso', models.DateField(blank=True, db_column='fechaCompromiso', null=True, verbose_name='Fecha compromiso')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=15)),
                ('controles', models.ManyToManyField(blank=True, db_table='hallazgoControles', related_name='hallazgos', to='controles.control', verbose_name='Requisito incumplido (Anexo A)')),
                ('direcciones', models.ManyToManyField(db_table='hallazgoDirecciones', related_name='hallazgos', to='activos.direccion', verbose_name='Proceso / Dirección')),
                ('tipos', models.ManyToManyField(db_table='hallazgoTipos', related_name='hallazgos', to='auditorias.tipohallazgo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'hallazgo de auditoría',
                'verbose_name_plural': 'hallazgos de auditoría',
                'db_table': 'hallazgo',
                'ordering': ['-fecha_deteccion', '-id'],
            },
        ),
    ]
