# Generated by Django 6.1 on 2026-08-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0002_seed_tipos_hallazgo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallazgo',
            name='accion_correctiva',
        ),
        migrations.RemoveField(
            model_name='hallazgo',
            name='fecha_compromiso',
        ),
        migrations.RemoveField(
            model_name='hallazgo',
            name='responsable',
        ),
    ]
