# Generated by Django 6.1 on 2026-08-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0009_seed_direcciones_hallazgos'),
        ('auditorias', '0003_remove_hallazgo_accion_correctiva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallazgo',
            name='direcciones',
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='procesos',
            field=models.ManyToManyField(db_table='hallazgoProcesos', related_name='hallazgos', to='activos.proceso', verbose_name='Proceso'),
        ),
    ]
