# Generated by Django 6.1 on 2026-08-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0004_remove_hallazgo_direcciones_hallazgo_procesos'),
        ('controles', '0009_seed_numerales_norma'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallazgo',
            name='numerales',
            field=models.ManyToManyField(blank=True, db_table='hallazgoNumerales', related_name='hallazgos', to='controles.numeralnorma', verbose_name='Requisito incumplido (numeral de la norma)'),
        ),
    ]
