# Generated by Django 6.1 on 2026-08-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0005_hallazgo_numerales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallazgo',
            options={'ordering': ['id'], 'verbose_name': 'hallazgo de auditoría', 'verbose_name_plural': 'hallazgos de auditoría'},
        ),
    ]
