# Generated by Django 6.1 on 2026-08-29 21:13

import apps.auditorias.models
import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0006_alter_hallazgo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoHallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('accion_correctiva', models.TextField(blank=True, db_column='accionCorrectiva', verbose_name='Acción correctiva')),
                ('fecha_compromiso', models.DateField(blank=True, db_column='fechaCompromiso', null=True, verbose_name='Fecha compromiso')),
                ('responsable', models.CharField(blank=True, max_length=250, verbose_name='Responsable')),
                ('fecha_seguimiento', models.DateField(blank=True, db_column='fechaSeguimiento', null=True, verbose_name='Fecha de seguimiento')),
                ('avance_notas', models.TextField(blank=True, db_column='avanceNotas', verbose_name='Avance / Notas')),
                ('verificacion_eficacia', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EFICAZ', 'Eficaz'), ('NO_EFICAZ', 'No eficaz')], db_column='verificacionEficacia', default='PENDIENTE', max_length=15, verbose_name='Verificación de eficacia')),
                ('hallazgo', models.ForeignKey(db_column='hallazgoId', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='auditorias.hallazgo')),
            ],
            options={
                'verbose_name': 'seguimiento de hallazgo',
                'verbose_name_plural': 'seguimientos de hallazgo',
                'db_table': 'seguimientoHallazgo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjuntoSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=255, upload_to=apps.auditorias.models.ruta_evidencia_seguimiento, validators=[apps.core.validators.validar_extension_archivo, apps.core.validators.validar_tamano_archivo], verbose_name='Archivo')),
                ('subido_en', models.DateTimeField(auto_now_add=True, db_column='subidoEn')),
                ('seguimiento', models.ForeignKey(db_column='seguimientoId', on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='auditorias.seguimientohallazgo')),
            ],
            options={
                'verbose_name': 'evidencia de cierre',
                'verbose_name_plural': 'evidencias de cierre',
                'db_table': 'archivoAdjuntoSeguimiento',
                'ordering': ['-subido_en'],
            },
        ),
    ]
