# Generated by Django 6.1 on 2026-08-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0007_seguimientohallazgo_archivoadjuntoseguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientohallazgo',
            name='verificacion_eficacia',
            field=models.CharField(choices=[('EFICAZ', 'Eficaz'), ('PARCIALMENTE_EFICAZ', 'Parcialmente Eficaz'), ('INEFICAZ', 'Ineficaz (No Cumple)'), ('NO_IMPLEMENTADO', 'No Implementado')], db_column='verificacionEficacia', default='NO_IMPLEMENTADO', max_length=20, verbose_name='Verificación de eficacia'),
        ),
    ]
