# Generated by Django 6.1 on 2026-08-29 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0008_alter_seguimientohallazgo_verificacion_eficacia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientohallazgo',
            name='responsable',
        ),
        migrations.AddField(
            model_name='seguimientohallazgo',
            name='responsables',
            field=models.ManyToManyField(blank=True, db_table='seguimientoHallazgoResponsables', related_name='seguimientos_hallazgo_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Responsables'),
        ),
    ]
