# Generated by Django 6.1 on 2026-08-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0009_remove_seguimientohallazgo_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallazgo',
            name='estado',
        ),
    ]
