# Generated by Django 6.1 on 2026-09-22 19:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_empleados_desde_usuarios'),
        ('activos', '0011_revisionsemestralactivos_snapshotactivo'),
        ('auditorias', '0010_remove_hallazgo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('ORDINARIA', 'Ordinaria (del programa anual)'), ('EXTRAORDINARIA', 'Extraordinaria')], default='ORDINARIA', max_length=20)),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('EN_EJECUCION', 'En ejecución'), ('CERRADA', 'Cerrada')], default='PLANIFICADA', max_length=20)),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo de la auditoría')),
                ('alcance', models.TextField(blank=True, verbose_name='Alcance de la auditoría')),
                ('criterios', models.TextField(blank=True)),
                ('metodologia', models.TextField(blank=True, verbose_name='Metodología de la auditoría')),
                ('numero_auditados', models.PositiveIntegerField(blank=True, db_column='numeroAuditados', null=True)),
                ('numero_auditores', models.PositiveIntegerField(blank=True, db_column='numeroAuditores', null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('fecha_auditoria', models.DateField(blank=True, db_column='fechaAuditoria', null=True, verbose_name='Fecha de auditoría')),
                ('fecha_elaboracion_informe', models.DateField(blank=True, db_column='fechaElaboracionInforme', null=True, verbose_name='Fecha de elaboración del informe')),
                ('conclusiones_generales', models.TextField(blank=True, db_column='conclusionesGenerales')),
                ('aprobado_por', models.ForeignKey(blank=True, db_column='aprobadoPorId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_aprobadas', to='accounts.empleado')),
                ('auditor_lider', models.ForeignKey(blank=True, db_column='auditorLiderId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_lideradas', to='accounts.empleado')),
                ('equipo_auditor', models.ManyToManyField(blank=True, db_table='auditoriaEquipoAuditor', related_name='auditorias_equipo', to='accounts.empleado')),
            ],
            options={
                'verbose_name': 'auditoría',
                'verbose_name_plural': 'auditorías',
                'db_table': 'auditoria',
                'ordering': ['-fecha_auditoria', '-id'],
            },
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='auditoria',
            field=models.ForeignKey(blank=True, db_column='auditoriaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos', to='auditorias.auditoria', verbose_name='Auditoría de origen'),
        ),
        migrations.CreateModel(
            name='OportunidadPlanAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oportunidad', models.CharField(db_column='nombreOportunidad', max_length=255)),
                ('medida_aprovechar', models.TextField(blank=True, db_column='medidaAprovechar')),
                ('evidencia', models.TextField(blank=True)),
                ('auditoria', models.ForeignKey(db_column='auditoriaId', on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades_plan', to='auditorias.auditoria')),
                ('responsable', models.ForeignKey(blank=True, db_column='responsableId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.empleado')),
            ],
            options={
                'verbose_name': 'oportunidad del plan de auditoría',
                'verbose_name_plural': 'oportunidades del plan de auditoría',
                'db_table': 'oportunidadPlanAuditoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('anio', models.PositiveIntegerField(db_column='anio', verbose_name='Año')),
                ('tipo', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa')], default='INTERNA', max_length=10)),
                ('auditado', models.CharField(blank=True, help_text='Para auditorías externas (proveedor, ente certificador, etc.).', max_length=200)),
                ('procedimiento', models.CharField(blank=True, max_length=200)),
                ('servicio_o_proyecto', models.CharField(blank=True, db_column='servicioOProyecto', max_length=200)),
                ('mes_planeado', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], db_column='mesPlaneado', null=True)),
                ('auditor_lider', models.ForeignKey(blank=True, db_column='auditorLiderId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_auditoria_liderados', to='accounts.empleado')),
                ('proceso', models.ForeignKey(blank=True, db_column='procesoId', help_text='Para auditorías internas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programas_auditoria', to='activos.proceso')),
            ],
            options={
                'verbose_name': 'programa de auditoría (fila anual)',
                'verbose_name_plural': 'programa de auditorías (filas anuales)',
                'db_table': 'programaAuditoria',
                'ordering': ['-anio', 'mes_planeado'],
            },
        ),
        migrations.AddField(
            model_name='auditoria',
            name='programa',
            field=models.ForeignKey(blank=True, db_column='programaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='auditorias.programaauditoria'),
        ),
        migrations.CreateModel(
            name='RiesgoPlanAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_riesgo', models.CharField(db_column='nombreRiesgo', max_length=255)),
                ('accion_control', models.TextField(blank=True, db_column='accionControl')),
                ('evidencia', models.TextField(blank=True)),
                ('auditoria', models.ForeignKey(db_column='auditoriaId', on_delete=django.db.models.deletion.CASCADE, related_name='riesgos_plan', to='auditorias.auditoria')),
                ('responsable', models.ForeignKey(blank=True, db_column='responsableId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.empleado')),
            ],
            options={
                'verbose_name': 'riesgo del plan de auditoría',
                'verbose_name_plural': 'riesgos del plan de auditoría',
                'db_table': 'riesgoPlanAuditoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SesionAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, db_column='horaInicio', null=True)),
                ('hora_fin', models.TimeField(blank=True, db_column='horaFin', null=True)),
                ('procedimiento', models.CharField(blank=True, max_length=200)),
                ('requisitos_a_auditar', models.TextField(blank=True, db_column='requisitosAAuditar')),
                ('auditado', models.CharField(blank=True, help_text='Persona o responsable del proceso auditado.', max_length=200)),
                ('auditor', models.ForeignKey(blank=True, db_column='auditorId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_auditor', to='accounts.empleado')),
                ('auditoria', models.ForeignKey(db_column='auditoriaId', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='auditorias.auditoria')),
                ('proceso', models.ForeignKey(blank=True, db_column='procesoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_auditoria', to='activos.proceso')),
            ],
            options={
                'verbose_name': 'sesión de auditoría (cronograma)',
                'verbose_name_plural': 'sesiones de auditoría (cronograma)',
                'db_table': 'sesionAuditoria',
                'ordering': ['fecha', 'hora_inicio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemVerificacionAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(blank=True, choices=[('P', 'Planear'), ('H', 'Hacer'), ('V', 'Verificar'), ('A', 'Actuar')], max_length=1)),
                ('descripcion_elemento', models.TextField(db_column='descripcionElemento', verbose_name='Descripción del elemento a revisar')),
                ('requisito_iso', models.CharField(blank=True, db_column='requisitoIso', max_length=255, verbose_name='Requisito ISO asociado')),
                ('otros_requisitos', models.TextField(blank=True, db_column='otrosRequisitos', verbose_name='Otros requisitos (norma, ley, resolución, documentos organizacionales)')),
                ('tipo_hallazgo', models.CharField(blank=True, choices=[('CONFORMIDAD', 'Conformidad'), ('NO_CONFORMIDAD', 'No Conformidad'), ('OPORTUNIDAD_MEJORA', 'Oportunidad de Mejora'), ('FORTALEZA', 'Fortaleza')], db_column='tipoHallazgo', max_length=20)),
                ('descripcion_hallazgo', models.TextField(blank=True, db_column='descripcionHallazgo')),
                ('auditoria', models.ForeignKey(db_column='auditoriaId', on_delete=django.db.models.deletion.CASCADE, related_name='items_verificacion', to='auditorias.auditoria')),
                ('hallazgo_generado', models.ForeignKey(blank=True, db_column='hallazgoGeneradoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_verificacion_origen', to='auditorias.hallazgo')),
                ('sesion', models.ForeignKey(blank=True, db_column='sesionId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_verificacion', to='auditorias.sesionauditoria')),
            ],
            options={
                'verbose_name': 'item de lista de verificación de auditoría',
                'verbose_name_plural': 'items de lista de verificación de auditoría',
                'db_table': 'itemVerificacionAuditoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MatrizPriorizacionAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('anio', models.PositiveIntegerField(db_column='anio', verbose_name='Año')),
                ('criticidad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Criticidad del proceso o activo (1-5)')),
                ('auditorias_previas', models.PositiveSmallIntegerField(db_column='auditoriasPrevias', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Resultados de auditorías previas (1-5)')),
                ('cambios', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Cambios significativos (1-5)')),
                ('incidentes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Incidentes de seguridad (1-5)')),
                ('legales', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Requisitos legales/regulatorios (1-5)')),
                ('relevancia', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Relevancia estratégica (1-5)')),
                ('riesgo_residual', models.PositiveSmallIntegerField(db_column='riesgoResidual', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Riesgo residual (1-5)')),
                ('proceso', models.ForeignKey(db_column='procesoId', on_delete=django.db.models.deletion.PROTECT, related_name='prioridades_auditoria', to='activos.proceso')),
            ],
            options={
                'verbose_name': 'matriz de priorización de auditoría',
                'verbose_name_plural': 'matriz de priorización de auditorías',
                'db_table': 'matrizPriorizacionAuditoria',
                'ordering': ['-anio', 'proceso__nombre'],
                'constraints': [models.UniqueConstraint(fields=('proceso', 'anio'), name='matrizPriorizacionAuditoria_proceso_anio_unico')],
            },
        ),
    ]
