# Generated by Django 6.1 on 2026-09-22 19:43

from django.db import migrations

# Datos reales tomados de MT-860-05-Matriz Priorizacion Auditorias AnasWayuu V 1.0.xlsx
# (carpeta Auditoria/9.2 auditoria interna/ del repo, no versionada en git). El nombre a
# la izquierda es el de la matriz; a la derecha, el nombre real en apps.activos.Proceso
# — hay dos con tilde/palabra distinta (probable error de tipeo en la carga original de
# Proceso, no en la matriz): "Auditoria" sin tilde en vez de "Auditoría", y "Gestión
# Ética y Cultural" en vez de "Gestión Étnica y Cultural" (esta EPSI es de salud
# indígena — "Étnica" concuerda con el resto del procedimiento PD-860-12, que también
# dice "Gestión Étnica y Cultural"). Se mapea aquí sin renombrar el Proceso existente,
# que es dato de producción fuera del alcance de este cambio.
FILAS_MATRIZ = [
    # (nombre_en_proceso, criticidad, auditorias_previas, cambios, incidentes, legales, relevancia, riesgo_residual)
    ('Direccionamiento Estratégico', 5, 4, 3, 3, 5, 5, 4),
    ('Gestión Ética y Cultural', 3, 3, 2, 1, 3, 4, 3),
    ('Gestión de la Calidad y Riesgos', 5, 5, 4, 4, 5, 5, 5),
    ('Comunicaciones', 3, 2, 2, 1, 2, 3, 2),
    ('Gestión del Aseguramiento', 5, 4, 3, 4, 5, 5, 4),
    ('Gestión del Riesgo en Salud', 5, 4, 3, 4, 5, 5, 4),
    ('Administrativa y Financiera', 4, 3, 3, 2, 4, 4, 3),
    ('Tecnología', 5, 4, 4, 5, 5, 5, 5),
    ('Auditoria', 4, 4, 3, 2, 4, 4, 4),
    ('Gestión Documental', 4, 3, 2, 1, 4, 3, 3),
    ('Gestión Humana', 4, 3, 2, 1, 4, 4, 3),
    ('Asesoría Jurídica', 4, 4, 3, 1, 5, 4, 3),
    ('Actuaria', 4, 3, 2, 1, 3, 4, 3),
]

ANIO_MATRIZ = 2025


def sembrar(apps, schema_editor):
    TipoHallazgo = apps.get_model('auditorias', 'TipoHallazgo')
    Proceso = apps.get_model('activos', 'Proceso')
    MatrizPriorizacionAuditoria = apps.get_model('auditorias', 'MatrizPriorizacionAuditoria')

    # FO-860-25 usa 4 tipos de hallazgo: Conformidad, No Conformidad, Oportunidad de
    # Mejora, Fortaleza. NC ya existe; "Acción de mejora" (AM) ya existente cubre el rol
    # de "Oportunidad de Mejora" (se reutiliza, no se duplica ni se renombra: ya hay 17
    # hallazgos reales usando estos códigos). Solo faltan Conformidad y Fortaleza.
    TipoHallazgo.objects.get_or_create(codigo='CONF', defaults={'nombre': 'Conformidad'})
    TipoHallazgo.objects.get_or_create(codigo='FORT', defaults={'nombre': 'Fortaleza'})

    for nombre_proceso, criticidad, auditorias_previas, cambios, incidentes, legales, relevancia, riesgo_residual in FILAS_MATRIZ:
        proceso = Proceso.objects.filter(nombre=nombre_proceso).first()
        if not proceso:
            continue
        MatrizPriorizacionAuditoria.objects.get_or_create(
            proceso=proceso,
            anio=ANIO_MATRIZ,
            defaults={
                'criticidad': criticidad,
                'auditorias_previas': auditorias_previas,
                'cambios': cambios,
                'incidentes': incidentes,
                'legales': legales,
                'relevancia': relevancia,
                'riesgo_residual': riesgo_residual,
            },
        )


def deshacer(apps, schema_editor):
    TipoHallazgo = apps.get_model('auditorias', 'TipoHallazgo')
    MatrizPriorizacionAuditoria = apps.get_model('auditorias', 'MatrizPriorizacionAuditoria')
    MatrizPriorizacionAuditoria.objects.filter(anio=ANIO_MATRIZ).delete()
    TipoHallazgo.objects.filter(codigo__in=['CONF', 'FORT']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0011_auditoria_hallazgo_auditoria_and_more'),
    ]

    operations = [
        migrations.RunPython(sembrar, deshacer),
    ]
