# Generated by Django 6.1 on 2026-09-22 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_revisionsemestralactivos_snapshotactivo'),
        ('auditorias', '0012_seed_tipos_hallazgo_y_matriz_priorizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionauditoria',
            name='tema',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tema / dominio auditado'),
        ),
        migrations.AlterField(
            model_name='oportunidadplanauditoria',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riesgoplanauditoria',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sesionauditoria',
            name='auditado',
            field=models.TextField(blank=True, help_text='Persona(s) o rol(es) del proceso auditado.'),
        ),
        migrations.AlterField(
            model_name='sesionauditoria',
            name='proceso',
            field=models.ForeignKey(blank=True, db_column='procesoId', help_text='Solo cuando la sesión corresponde exactamente a un proceso del catálogo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_auditoria', to='activos.proceso'),
        ),
    ]
