# Generated by Django 6.1 on 2026-09-22 21:45

from django.db import migrations

# Datos reales tomados de "Auditoria Interna realizada 2025/20251205 Plan de auditoría
# V 1.1.xlsx" (carpeta Auditoria/9.2 auditoria interna/ del repo, no versionada en
# git) — una auditoría interna real, ejecutada por un auditor externo (Mauricio
# Mantilla Álvarez) del 9 al 11 de diciembre de 2025. Se carga para dejar trazabilidad
# de que esta auditoría ocurrió, aunque el usuario no aportó el Informe (FO-860-22) ni
# la Lista de verificación (FO-860-25) diligenciados — por eso no hay hallazgos reales
# que cargar, solo el Plan y el cronograma ejecutado.
CODIGO_AUDITORIA = 'AUD-2025-001'

RIESGOS_PLAN = [
    (
        'Planificación incorrecta del ejercicio por desconocimiento de aspectos '
        'específicos de la organización y su SGSI',
        'Revisión documental\nRevisión y aprobación del plan por el líder del SGSI',
        'Auditor líder\nLíder del SGSI',
        'Solicitud de información\nPlan revisado y aprobado',
    ),
    (
        'Incumplimiento del plan de auditoría por indisponibilidad de los auditados',
        'Comunicación previa del plan a todos los involucrados\nMonitoreo continuo del '
        'avance de ejecución frente al plan',
        'Líder del SGSI\nAuditor Líder',
        'Registro de la comunicación',
    ),
]

OPORTUNIDADES_PLAN = [
    (
        'Alinear las fechas de la auditoría con la disponibilidad del personal '
        'involucrado en el SGSI',
        'Coordinación operativa con el auditor líder y los auditados',
        'Líder del SGSI',
        'Comunicaciones con los involucrados',
    ),
]

# (fecha, hora_inicio, hora_fin, ciudad, tema, proceso_nombre_o_None, procedimiento,
#  requisitos_a_auditar, auditado)
SESIONES = [
    ('2025-12-09', '08:00', '09:00', 'Maicao', 'Reunión de apertura', None,
     'PD-860-12 Procedimiento de Auditorias Internas V 1.0', 'N/A', 'Todos'),
    ('2025-12-09', '09:00', '10:30', 'Maicao', 'Planificación del SGSI', None,
     'MP-860-01 Manual Sistema de Gestión de Seguridad de la Información V. 2.0',
     '4,5,6.2,6.3, 7.1, 7.4, 7.5, 8.1 A5.1 a 4, 31,34,37', 'Gerencia\nLíder del SGSI'),
    ('2025-12-09', '10:30', '12:00', 'Maicao', 'Gestión de Riesgos de Seguridad de la Información', None,
     'Guía para la Gestión de Riesgos y Oportunidades de Seguridad de la Información',
     '6.1, 8.2, 8.3, A5.7 a 9', 'Responsable de riesgos'),
    ('2025-12-09', '13:30', '14:30', 'Maicao', 'Gestión Humana', 'Gestión Humana',
     'Manual de Funciones\nPolítica de Seguridad de la Información en los Recursos Humanos\n'
     'Plan de Capacitaciones', '5.3, 7.2, 7.3. A5.2, 3, A6',
     'Jefe de Oficina de Gestión Humana, equipo de trabajo\nLíder SGSI'),
    ('2025-12-09', '14:30', '15:30', 'Maicao', 'Seguridad terceros', None,
     'Política para la seguridad de las relaciones con proveedores', '8.1, A.5.19 a 23',
     'Director de Contratación y Planeación, equipo de trabajo\nLíder SGSI'),
    ('2025-12-09', '15:30', '16:30', 'Maicao', 'Infraestructura y Comunicaciones', None,
     'Guía para la Gestión de Riesgos y Oportunidades de Seguridad de la Información',
     'A6.7, A7.13, A8.2, 6, 8 a 10, 12, 13, 18 a 25', 'Jefe de Tecnología y comunicaciones, equipo de trabajo'),
    ('2025-12-09', '16:30', '17:30', 'Maicao', 'Computación de usuario final', None,
     'Guía para la Gestión de Riesgos y Oportunidades de Seguridad de la Información',
     'A5.11, 16 a 18, 32 A6.8, A8.1,10', 'Jefe de Tecnología y comunicaciones, equipo de trabajo'),
    ('2025-12-10', '09:30', None, 'Manaure', 'Visita Sede Manaure', None,
     'MP-860-01 Manual Sistema de Gestión de Seguridad de la Información V. 2.0',
     '5.2, 7.3, A6.2 y 3  A6.8, A7, A5.10, 12 a 15, 33', 'Funcionarios del área'),
    ('2025-12-10', '14:30', None, 'Uribia', 'Visita Sede Uribia', None,
     'MP-860-01 Manual Sistema de Gestión de Seguridad de la Información V. 2.0',
     '5.2, 7.3, A6.2 y 3  A6.8, A7, A5.10, 12 a 15, 33', 'Funcionarios del área'),
    ('2025-12-11', '08:00', '09:00', 'Maicao', 'Desarrollo y sistemas', None,
     'Guía para la Gestión de Riesgos y Oportunidades de Seguridad de la Información',
     'A5.15, A8.3 a 5, A8.11, 26 a 32', 'Jefe de Programación, equipo de desarrollo'),
    ('2025-12-11', '09:00', '10:00', 'Maicao', 'Seguridad física', None,
     'Guía para la Gestión de Riesgos y Oportunidades de Seguridad de la Información',
     'A.7.1 a 6, A7.9', 'DAF'),
    ('2025-12-11', '10:00', '12:00', 'Maicao', 'Gestión de Incidentes', None,
     'Guía de Gestión y Clasificación de Incidentes de SI',
     'A.5.5, 6, A5 24 a 28, A8.7, 15 a 17', 'Líder SGSI'),
    ('2025-12-11', '14:00', '15:00', 'Maicao', 'Gestión de continuidad de la TI', None,
     'Plan de Continuidad y Recuperación TI', 'A5.29, 30, A8.13, 14', 'Líder SGSI'),
    ('2025-12-11', '15:00', '15:30', 'Maicao', 'Seguimiento y evaluación', None,
     'MP-860-01 Manual Sistema de Gestión de Seguridad de la Información V. 2.0',
     '9.1, 9.2, 10.2, A5.35, 36 A8.34', 'Líder SGSI / Aseguramiento'),
    ('2025-12-11', '15:30', '16:00', 'Maicao', 'Revisión por la dirección, mejora', None,
     'MP-860-01 Manual Sistema de Gestión de Seguridad de la Información V. 2.0',
     '9.3, 10.1', 'Comité de Seguridad de la información'),
    ('2025-12-11', '17:00', '18:00', 'Maicao', 'Reunión de cierre', None,
     'PD-860-12 Procedimiento de Auditorias Internas V 1.0', 'N/A', 'Todos'),
]


def sembrar(apps, schema_editor):
    Empleado = apps.get_model('accounts', 'Empleado')
    Proceso = apps.get_model('activos', 'Proceso')
    Auditoria = apps.get_model('auditorias', 'Auditoria')
    RiesgoPlanAuditoria = apps.get_model('auditorias', 'RiesgoPlanAuditoria')
    OportunidadPlanAuditoria = apps.get_model('auditorias', 'OportunidadPlanAuditoria')
    SesionAuditoria = apps.get_model('auditorias', 'SesionAuditoria')

    if Auditoria.objects.filter(codigo=CODIGO_AUDITORIA).exists():
        return

    auditor, _ = Empleado.objects.get_or_create(
        nombre_completo='Mauricio Mantilla Álvarez',
        defaults={'cargo': 'Auditor Líder (externo)', 'correo': '', 'activo': True},
    )

    auditoria = Auditoria.objects.create(
        codigo=CODIGO_AUDITORIA,
        programa=None,
        tipo='ORDINARIA',
        estado='CERRADA',
        objetivo=(
            '1) Evaluar la conformidad del SGSI con los requisitos propios de la '
            'organización \n2) Evaluar la conformidad del SGSI frente a los requisitos '
            'de ISO/IEC 27001:2022;\n3) Confirmar que el SGSI se implementa y mantiene '
            'eficazmente.'
        ),
        alcance=(
            'Todo el alcance del SGSI que contempla los procesos de Seguridad de la '
            'Información en la gestión, almacenamiento y protección de la información '
            'administrativa y de prestación de servicios en salud de los afiliados, '
            'incluyendo los sistemas de información de los procesos de gestión del '
            'aseguramiento y gestión del riesgo en salud.'
        ),
        criterios=(
            'ISO/IEC 27001:2022. \nLos requisitos establecidos por la organización en '
            'sus disposiciones documentadas'
        ),
        metodologia='Entrevistas, revisión documental, observación de actividades, de forma presencial',
        numero_auditados=None,
        numero_auditores=1,
        auditor_lider=auditor,
        ciudad='Maicao',
        fecha_auditoria='2025-12-09',
        fecha_elaboracion_informe=None,
        conclusiones_generales=(
            'Auditoría realizada por un auditor externo (Mauricio Mantilla Álvarez) del '
            '9 al 11 de diciembre de 2025. El usuario no aportó el Informe de Auditoría '
            '(FO-860-22) ni la Lista de Verificación (FO-860-25) diligenciados — solo el '
            'Plan de Auditoría (FO-860-24), que es lo que queda cargado aquí como '
            'trazabilidad. Si se cuenta con el informe real, actualizar este registro '
            'con hallazgos y conclusiones reales.'
        ),
        aprobado_por=None,
    )

    for nombre_riesgo, accion_control, responsable, evidencia in RIESGOS_PLAN:
        RiesgoPlanAuditoria.objects.create(
            auditoria=auditoria, nombre_riesgo=nombre_riesgo, accion_control=accion_control,
            responsable=responsable, evidencia=evidencia,
        )

    for nombre_oportunidad, medida_aprovechar, responsable, evidencia in OPORTUNIDADES_PLAN:
        OportunidadPlanAuditoria.objects.create(
            auditoria=auditoria, nombre_oportunidad=nombre_oportunidad,
            medida_aprovechar=medida_aprovechar, responsable=responsable, evidencia=evidencia,
        )

    for fecha, hora_inicio, hora_fin, ciudad, tema, proceso_nombre, procedimiento, requisitos, auditado in SESIONES:
        proceso = Proceso.objects.filter(nombre=proceso_nombre).first() if proceso_nombre else None
        SesionAuditoria.objects.create(
            auditoria=auditoria, ciudad=ciudad, fecha=fecha, hora_inicio=hora_inicio, hora_fin=hora_fin,
            proceso=proceso, tema=tema, procedimiento=procedimiento, requisitos_a_auditar=requisitos,
            auditado=auditado, auditor=auditor,
        )


def deshacer(apps, schema_editor):
    Auditoria = apps.get_model('auditorias', 'Auditoria')
    Auditoria.objects.filter(codigo=CODIGO_AUDITORIA).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0013_sesionauditoria_tema_and_more'),
        ('accounts', '0008_seed_empleados_desde_usuarios'),
    ]

    operations = [
        migrations.RunPython(sembrar, deshacer),
    ]
