# -*- coding: utf-8 -*-
# Generated by Django 6.1 on 2026-09-22 22:10

import datetime

from django.db import migrations

# Datos reales tomados de FO-860-22-Informe de Auditoria Interna V 1.0.xlsx y
# FO-860-25-Lista de verificación de auditorías V 1.0.xlsx, ambos dentro de
# "Auditoria Interna realizada 2025/" (carpeta Auditoria/9.2 auditoria interna/ del
# repo, no versionada en git) — el informe y la lista de verificación reales de la
# auditoría AUD-2025-001 (sembrada en la migración 0014, solo con el Plan en ese
# momento; el usuario aportó después estos dos documentos adicionales).
#
# Extraídos con un script que escribe directo a un archivo .py en UTF-8 (sin pasar
# por la consola de Git Bash): imprimir texto con tildes a través de un pipe `>` en
# ese entorno lo reescribe con el codepage de la consola (cp1252), no UTF-8 — un
# problema real de corrupción de datos, no solo de visualización, detectado y
# corregido en el momento de construir esta migración. Ver ESTADO_PROYECTO.md.

CODIGO_AUDITORIA = 'AUD-2025-001'

FECHA_ELABORACION_INFORME = datetime.date(2025, 12, 22)

NOTA_ALCANCE = (
    '\n\nNOTA: En el requisito de auditorías internas se excluye la realización de '
    'la auditoría por principio de independencia'
)

CONCLUSIONES_GENERALES = (
    'Se observa un SGSI definido para atender los requisitos de ISO/IEC 27001:2022. \n'
    'El sistema ha sido definido recientemente y se encuentra en proceso de '
    'implementación. \n'
    'Las prácticas de gestión y los controles de seguridad de la información están '
    'descritos en la documentación del sistema siguiendo las mejores prácticas del '
    'mercado, lo cual puede ser un reto para su plena implementación en este sistema '
    'que, como se dijo antes, es bastante joven por lo que se recomienda evaluar una '
    'implementación progresiva de esas prácticas siguiendo los pasos de un modelo de '
    'madurez.\n'
    'Con el fin de lograr un nivel de eficacia acorde con las expectativas de los '
    'grupos de interés se sugiere asegurar la alineación de los procesos de análisis '
    'de riesgos y tratamiento con los estudios e informes de las empresas y '
    'entidades reconocidas en el mercado global de la seguridad, en el sentido de '
    'identificar y valorar el riesgo para la organización de los riesgos más '
    'relevantes en el mundo actual y de implementar prioritariamente las medidas de '
    'seguridad consideradas más eficaces para mitigar esos riesgos, de manera '
    'especial los riesgos del ciberespacio'
)

# (proceso, responsable, [fortalezas], [aspectos de mejora], [no conformidades],
#  ac_aspectos, ac_no_conformidades) — ac_* es la acción correctiva que el auditor ya
# dejó anotada (nombres de personas involucradas); se guarda en evidencia_asociada,
# no se intenta convertir en un Empleado/seguimiento real (nombres de pila
# ambiguos, sin apellido, no identificables con certeza en el directorio).
BLOQUES_INFORME = [
    ('Planificación del SGSI', 'Líder del SGSI',
     ['Análisis de contexto pertinente y específico de seguridad de la información',
      'Matriz de roles y funciones en el SGSI define claramente las responsabilidades en relación con el sistema'],
     ['Fortalecer la divulgación y seguimiento a las disposiciones del SGSI',
      'Especificar los procesos y roles en donde se segregan las funciones'],
     ['No se ha identificado los requisitos de seguridad de la información asociados a la regulación de historia clínica (4.2)',
      'No se cuenta con un enfoque documentado para el cumplimiento de cada uno de los requisitos legales relevantes y cuales serán abordados por el SGSI (A5.31)'],
     None,
     '1 AC 1. Definir el rol y la responsabilidad de la matriz de requisitos legales y confirmar lo mismo de la matriz de partes interesadas para Paola. 2. Incluir en la matriz de requisitos legales una columna donde se evidencie el documento que soporta el cumplimiento legal. (Proceso Jurídico (Nilda Gozález - Ayda Serrano - Paola - Germán).\n3. Buscar la normativa legal existente para el caso de las historias clínicas.'),
    ('Gestión de riesgos de SI', 'Responsable de riesgos',
     ['Análisis exhaustivo de riesgos de seguridad de la información'],
     ['Ajustar la metodología de análisis de riesgos con el fin de producir un conjunto más reducido y gestionable de riesgos asegurando la completa cobertura de los factores de riesgo relevantes'],
     ['No existe evidencia de que se han designado los dueños de los riesgos y asegurado el cumplimiento de sus responsabilidades como tales, entre ellas la aprobación de los correspondientes planes de tratamiento (6.1.2, 6.1.3)',
      'La declaración de aplicabilidad no contiene la justificación de la inclusión o la exclusión de controles y no incluye el estado de implementación de los mismos (6.1.3)'],
     None,
     '2AC AC Formalizar la asignación de dueños de riesgos y la aprobación de los planes tratamiento (realizar una evidencia documental) Oscar y Germán \n3AC Corrección: Revisar la declaración de aplicabilidad y ver cual fue la versión que se le presentó al auditor y verificar la existencia de las justificaciones. Oscar y Miguel'),
    ('Seguridad en el talento humano', 'Jefe de Oficina de Gestión Humana',
     ['La implementación del otrosí al contrato laboral sobre los aspectos de seguridad de la información',
      'El acuerdo de confidencialidad establecido con los funcionarios'],
     ['Fortalecer el programa de concienciación puesto que durante la auditoría se evidenció uso de contraseñas débiles, mal manejo de las mismas, controles no aplicados tales como puertas abiertas, archivadores con información confidencial sin seguridad, sesiones abiertas sin la presencia del funcionario'],
     ['No se encuentra evidencia de la verificación de requisitos de competencia establecidos en la matriz de roles'],
     'AC4 Oscar - Miguel',
     'AC5 Máxima - Germán'),
    ('Seguridad en procesos y servicios tercerizados', 'Director de Contratación y Planeación',
     ['Las clausulas de protección de datos y confidencialidad en los contratos con terceros relevantes',
      'La inclusión de aspectos de seguridad en auditoría de calidad realizada a procesos prioritarios'],
     ['Definir una lista de aspectos de seguridad a ser considerados cuando se planifica la contratación de un tercero'],
     ['No se evidencia análisis de riesgos y aceptación o acuerdos de control de terceros y su gestión en relación con servicios consumidos en la nube (A5.20)'],
     None,
     'AC6 Revisar la política de servicios de la nube para la AC. Se debe hacer cumplir la política. Rafael y Estela - Oscar - Miguel'),
    ('Infraestructura TI', 'Jefe de Tecnología y comunicaciones',
     ['El enfoque estratégico para soportar los servicios de TI en proveedores de nube con reconocidas prácticas de seguridad'],
     ['Analizar e implementar el modelo de responsabilidades de seguridad compartidas con los proveedores de nube'],
     ['No se observa evidencia de la implementación de controles críticos de infraestructura de tecnología como: gestión de configuración, gestión de vulnerabilidad técnica, fuga de datos, usuarios privilegiados (A8.2, A8.8, A8.9, A8.12)'],
     None,
     'AC 7 Se debe marcar cada acción de manera específica asociada a cada control en el plan de acción. Contratación de auditor interno y contratación de Oficial de Seguridad de la Información. Oscar - Miguel'),
    ('Aplicación de controles en areas operativas', 'Jefe de Tecnología y comunicaciones',
     ['Política de escritorio y pantalla limpios'],
     ['Desarrollar una comunicación para todos los empleados que incluya las recomendaciones de seguridad, aprovechando la experiencia con las cartillas dirigidas a los afiliados',
      'Incorporar a la red de monitoreo CCTV a la sede de Nazareth',
      'Fortalecer las medidas contingentes para contar con energía eléctrica en las sedes remotas más pequeñas para mitigar la inestabilidad de la red del prestador del servicio'],
     ['Se observa la no aplicación del control de protección de registros en relación con la apropiada seguridad de los documentos físicos en las sedes remotas en donde se observaron archivadores sin cerrar o con llaves en la cerradura, cerraduras que no funcionan, documentos confidenciales que se informa correspondían a funcionarios retirados que se encuentran sin reasignar, destruir o enviar al archivo central. (A5.33)',
      'No se evidencia la aplicación del control de etiquetado de información (A5.13)'],
     'AC8 Mildrey Oyaga - Oscar - Wilmar - Miguel',
     'AC9 Tener en cuenta la política de seguridad física definida. Se debe implementar los lineamientos de la política de personas y aplicarla. Aplicar las sanciones correspondientes definidas en los controles de personas. Mildrey Oyaga - Lasides Iguarán - Máxima - Oscar - Wilmar - Miguel\nAC10 Implementar el procedimiento de etiquetado. Mildrey Oyaga - Lasides Iguaran - Miguel'),
    ('Desarrollo de software', 'Jefe de Programación',
     ['Los recursos y tecnologías disponibles para el desarrollo'],
     ['Fortalecer la competencia en prácticas de seguridad en la construcción y operación segura de soluciones en el equipo de desarrollo'],
     ['No se evidencia un proceso de desarrollo seguro establecido y gestionado que asegure la implementación consistente de las medidas de seguridad de la información en los proyectos de desarrollo (requisitos de seguridad, principios de ingeniería, prácticas de desarrollo seguro, gestión de cambios, pruebas de seguridad, datos de prueba, ambientes controlados y efectivamente aislados tecnológica y procedimentalmente) (A.8.25 a 32)'],
     None,
     'AC 11 Revisar toda la documentación realizada y verificar su implementación. José Correa - Equipo de desarrollo - Miguel'),
    ('Seguridad física', 'DAF',
     ['La fortaleza de las prácticas de seguridad física evidenciada en la sede principal de Maicao en relación con el perímetro de seguridad, vigilancia monitoreada y el control de acceso a areas restringidas'],
     [],
     ['Se evidencia insuficiencia en las medidas de seguridad física aplicadas en el archivo central: documentos almacenados directamente en el piso, paredes con evidencia de humedad, ventanas sin seguridad, almacenamiento de materiales y elementos incompatibles con el propósito del área, extintor de incendios no se encontraba en la ubicación establecida (A7.3, A7.5, A5.33)'],
     None,
     'AC 12 Incorporar la política de seguridad física, incluir el plan de inversiones y mantenimiento y en el plan de gestión documental. Mildrey Oyaga - Oscar - Wilmar - Miguel'),
    ('Gestión de incidentes', 'Líder del SGSI',
     ['Guía para la gestión de incidentes'],
     [],
     ['Se observa que los relojes del teléfono inalámbrico del equipo de desarrollo y del control de acceso a gerencia no están sincronizados (A8.17)',
      'No se cuenta con un plan de respaldo documentado que establezca la periodicidad de las copias de seguridad y de las pruebas de restauración para cada tema específico (sistemas, infraestructura, software de base, datos y documentos de negocio, etc.) (A8.13)'],
     None,
     'AC 13 Revisar todos los sistemas que no se encuentren dentro del directorio activo. Oscar - Miguel\nAC 14 Elaborar el plan de respaldo y las pruebas de restauración. Considerar los requisitos legales y contractuales. Wilmar - Oscar - Miguel'),
    ('Continuidad de la TI', 'Líder del SGSI',
     ['La solución redundante implementada para la comunicación con las sedes remotas',
      'Disponibilidad de recursos (almacenamiento y procesamiento) para respaldo'],
     [],
     ['No se cuenta con plan de pruebas de los planes de continuidad de la TI (A5.30)'],
     None,
     'AC 15 No se han realizado ejercicios de verificación. Se deben realizar pruebas y validaciones, ej: una situación relacionada al tema de suministro de energía. Mildred Oyaga - Elibeth Bastidas - Wilmar - Oscar - José Correa - Miguel'),
    ('Seguimiento y evaluación del SGSI', 'Líder del SGSI',
     [],
     ['Implementar los indicadores diseñados y evaluar la conveniencia de otras opciones de seguimiento que faciliten el adecuado control de todos los procesos y controles del SGSI.'],
     [],
     'AC 16 No se tienen mediciones de indicadores. Depurar los indicadores y agruparlos para hacer un mejor control sobretodo en el tema de riesgos. Oscar - Paola - Maydred - Wilmar - Miguel - Germán',
     None),
    ('Revisión por la dirección y mejora', 'Líder del SGSI',
     [],
     [],
     ['No se encuentra evidencia de que la alta dirección ha revisado el SGSI y que ha tomado las decisiones de mejora pertinentes de acuerdo con la información y las propuestas presentadas por los responsables de los procesos del sistema (9.3)'],
     None,
     'AC 17 Definir la fecha de la RD. Yercine'),
]

# (clave_tipo, clave_valor, requisito_iso, tipo_hallazgo, descripcion_elemento, descripcion_hallazgo)
# clave_tipo/clave_valor identifican a qué SesionAuditoria (de las 16 creadas en la
# migración 0014) pertenece cada item: ('tema', '<texto>') empareja por
# SesionAuditoria.tema, ('proceso', '<nombre>') por SesionAuditoria.proceso.nombre,
# (None, None) queda sin sesión asociada (la hoja "Sedes" del checklist cubre las
# visitas a Manaure y Uribia genéricamente, sin corresponder a una sola sesión).
ITEMS_CHECKLIST = [
    ('tema', 'Planificación del SGSI', '4,5,6.2,6.3, 7.1, 7.4, 7.5, 8.1 A5.1 a 4, 31,34,37', 'FORTALEZA', 'Contexto', 'Pertinencia del análisis del contexto, específico de seguridad de la información'),
    ('tema', 'Planificación del SGSI', 'Requisitos legales A.5.31', 'NO_CONFORMIDAD', 'Requisitos legales A.5.31', 'No se ha identificado la regulación de historia clínica, no se cuenta con un enfoque documentado para el cumplimiento de los requisitos legales relevantes y cuales serán abordados del'),
    ('tema', 'Planificación del SGSI', '8.1 A5.1 a 4,34,37', 'CONFORMIDAD', '8.1 A5.1 a 4,34,37', ''),
    ('tema', 'Planificación del SGSI', '5.1', 'CONFORMIDAD', 'Liderazgo', ''),
    ('tema', 'Planificación del SGSI', '5.2', 'NO_CONFORMIDAD', '5.2', 'Enunciar los principales aspectos legales de cumplimiento en la política del SGSI'),
    ('tema', 'Planificación del SGSI', '6.2', 'NO_CONFORMIDAD', 'Objetivos', 'No se han implementado los indicadores para medir los objetivos del sgsi'),
    ('tema', 'Planificación del SGSI', '6.3', 'CONFORMIDAD', 'Planificacion de cambios', ''),
    ('tema', 'Planificación del SGSI', '7.1', 'CONFORMIDAD', 'Recursos', 'Identificados y controlados'),
    ('tema', 'Planificación del SGSI', '7.4', 'OPORTUNIDAD_MEJORA', 'Comunicación', 'Complementar la matriz de comunicaciones con las comunicaciones entrantes y con otras áreas involucradas en el sgsi'),
    ('tema', 'Planificación del SGSI', '7.5', 'OPORTUNIDAD_MEJORA', 'Documentación', 'Revisar la documentación del sgsi en el sentido de iniciar la implementación con las acciones fundamentales de cada proceso y progresivamente ir fortaleciendolas con mejores prácticas en la medida que las herramientas de seguimiento lo indiquen necesario'),
    ('tema', 'Planificación del SGSI', 'A5.2', 'OPORTUNIDAD_MEJORA', 'Roles y responsabilidades', 'Gestionar evidencia de la comunicación a los designados su el rol en el SGSI'),
    ('tema', 'Planificación del SGSI', 'A5.3', 'OPORTUNIDAD_MEJORA', 'A5.3', 'Especificar los procesos en donde se aplica la segregación de funciones'),
    ('tema', 'Gestión de Riesgos de Seguridad de la Información', '6.1, 8.2, 8,3, A5.7 a 9', 'NO_CONFORMIDAD', 'Gestión de riesgos de seguridad de la información', 'No existe evidencia de la identificación de oportunidades del sgsi'),
    ('tema', 'Gestión de Riesgos de Seguridad de la Información', '6.1.2, 8.2', 'OPORTUNIDAD_MEJORA', '6.1.2, 8.2', 'Considerar una modificación a la metodología de identificación de riesgos con el fin de reducir el detalle de cada riesgo asociado a cada causa'),
    ('tema', 'Gestión de Riesgos de Seguridad de la Información', '6.1.3, 8.3', 'NO_CONFORMIDAD', '6.1.3, 8.3', 'el plan de tratamiento de riesgos no incluye los controles impleentados. SOA no tiene estado de impementación, la justificación no es)'),
    ('tema', 'Gestión de Riesgos de Seguridad de la Información', '6.1.3, 8.3', 'NO_CONFORMIDAD', '6.1.3, 8.3', 'No se cuenta con evidencia de la aprobación del plan de tratamiento de riesgos (matriz de riesgos)'),
    ('tema', 'Gestión de Riesgos de Seguridad de la Información', 'A5.7', 'CONFORMIDAD', 'A5.7', 'Definido'),
    ('tema', 'Gestión de Riesgos de Seguridad de la Información', 'A5.8', 'CONFORMIDAD', 'A5.8', 'Definido'),
    ('tema', 'Gestión de Riesgos de Seguridad de la Información', 'A5.9', 'OPORTUNIDAD_MEJORA', 'A5.9', 'Ver en gestión de configuración'),
    ('proceso', 'Gestión Humana', '5.3, 7.2, 7.3, A5.2 y 3, A6.1 a 6', 'CONFORMIDAD', 'Seguridad en Gestión Humana', ''),
    ('proceso', 'Gestión Humana', '7.2', 'NO_CONFORMIDAD', '7.2', 'Implementar evidencia del control de verificación de requisitos de competencia e incluyendo los requisitos de los roles definidos en la matriz'),
    ('proceso', 'Gestión Humana', '7.3', 'OPORTUNIDAD_MEJORA', '7.3', 'Consolidar acciones'),
    ('proceso', 'Gestión Humana', 'A5.2', 'CONFORMIDAD', 'A5.2', ''),
    ('proceso', 'Gestión Humana', 'A5.3', 'CONFORMIDAD', 'A5.3', ''),
    ('proceso', 'Gestión Humana', 'A6.1', 'CONFORMIDAD', 'A6.1', 'Lista de verificación'),
    ('proceso', 'Gestión Humana', 'A6.2', 'FORTALEZA', 'A6.2', 'Otrosí y acuerdo de confidencialidad'),
    ('proceso', 'Gestión Humana', 'A6.3', 'CONFORMIDAD', 'A6.3', ''),
    ('proceso', 'Gestión Humana', 'A6.4', 'CONFORMIDAD', 'A6.4', 'Reglamento de trabajo en curso de revisión por la reforma e iso 27001. El mal uso de la información es falta gravísima'),
    ('proceso', 'Gestión Humana', 'A6.5', 'CONFORMIDAD', 'A6.5', ''),
    ('proceso', 'Gestión Humana', 'A6.6', 'CONFORMIDAD', 'A6.6', ''),
    ('tema', 'Seguridad terceros', '8.1, A.5.19 a 23', 'OPORTUNIDAD_MEJORA', 'Seguridad en procesos y servicios tercerizados', 'Se evidencia cláusula de protección de datos y cláusula de confidencialidad. auditorías de calidad al prestador. Estandar de procesos prioritarios: Resolución 3100 de 2019: la hace dirección de auditoría.\nSGSI proponer una lista de aspectos de seguridad'),
    ('tema', 'Seguridad terceros', 'A5.19 Seguridad de la información en las relaciones con el proveedor', 'CONFORMIDAD', 'A5.19 Seguridad de la información en las relaciones con el proveedor', ''),
    ('tema', 'Seguridad terceros', 'A5.20 Abordar la seguridad de la información dentro de los acuerdos con proveedores', 'NO_CONFORMIDAD', 'A5.20 Abordar la seguridad de la información dentro de los acuerdos con proveedores', 'no se evidencia análisis de riesgos y/o disposiciones para seguridad de la información en el servicio de workspace'),
    ('tema', 'Seguridad terceros', 'A5.21 Gestión de la seguridad de la información en la cadena de suministro de la tecnología de la información y la comunicación (TIC)', 'OPORTUNIDAD_MEJORA', 'A5.21 Gestión de la seguridad de la información en la cadena de suministro de la tecnología de la información y la comunicación (TIC)', 'Evaluar pertinencia'),
    ('tema', 'Seguridad terceros', 'A5.22 Seguimiento, revisión y gestión del cambio de los servicios de los proveedores', 'CONFORMIDAD', 'A5.22 Seguimiento, revisión y gestión del cambio de los servicios de los proveedores', ''),
    ('tema', 'Seguridad terceros', 'A5.23 Seguridad de la información para el uso de servicios en la nube', 'OPORTUNIDAD_MEJORA', 'A5.23 Seguridad de la información para el uso de servicios en la nube', 'Desarrollar el modelo de responsabilidades compartidas'),
    ('tema', 'Infraestructura y Comunicaciones', 'A6.7, A7.13, A8.2, 6, 8 a 10, 12, 13, 18 a 24', 'CONFORMIDAD', 'Infraestructura TI', ''),
    ('tema', 'Infraestructura y Comunicaciones', 'a7.13 mtto de equipos', 'CONFORMIDAD', 'a7.13 mtto de equipos', ''),
    ('tema', 'Infraestructura y Comunicaciones', 'a8.2 acceso privilegiado', 'NO_CONFORMIDAD', 'a8.2 acceso privilegiado', 'Se identifica contraseñas débiles de administracion'),
    ('tema', 'Infraestructura y Comunicaciones', 'a8.6 capacidad', 'CONFORMIDAD', 'a8.6 capacidad', ''),
    ('tema', 'Infraestructura y Comunicaciones', 'a 8.8. vulnerabilidad tecnica', 'NO_CONFORMIDAD', 'a 8.8. vulnerabilidad tecnica', 'No existe evidencia de implementación'),
    ('tema', 'Infraestructura y Comunicaciones', 'a8.9 gestion de configuración', 'NO_CONFORMIDAD', 'a8.9 gestion de configuración', 'No existe evidencia de implementación'),
    ('tema', 'Infraestructura y Comunicaciones', 'a8,12 fuga', 'NO_CONFORMIDAD', 'a8,12 fuga', 'No se cuenta con una solución que implemente la prevención de fuga de datos'),
    ('tema', 'Infraestructura y Comunicaciones', 'a8 13 copias', 'CONFORMIDAD', 'a8 13 copias', ''),
    ('tema', 'Infraestructura y Comunicaciones', 'a8.18 Uso de programas de utilidad privilegiados', 'CONFORMIDAD', 'a8.18 Uso de programas de utilidad privilegiados', 'Política'),
    ('tema', 'Infraestructura y Comunicaciones', 'a8.19 Instalación de software en sistemas operativos', 'CONFORMIDAD', 'a8.19 Instalación de software en sistemas operativos', 'Personal IT'),
    ('tema', 'Infraestructura y Comunicaciones', 'a8.20 Seguridad de redes', 'CONFORMIDAD', 'a8.20 Seguridad de redes', 'Firewall'),
    ('tema', 'Infraestructura y Comunicaciones', 'a8.21 Seguridad de los servicios de red', 'CONFORMIDAD', 'a8.21 Seguridad de los servicios de red', ''),
    ('tema', 'Infraestructura y Comunicaciones', 'a8.22 Segregación de redes', 'CONFORMIDAD', 'a8.22 Segregación de redes', 'Segmentación'),
    ('tema', 'Infraestructura y Comunicaciones', 'a8.23 Filtrado web', 'CONFORMIDAD', 'a8.23 Filtrado web', 'Implementado'),
    ('tema', 'Infraestructura y Comunicaciones', 'a8.24 Uso de la criptografía', 'CONFORMIDAD', 'a8.24 Uso de la criptografía', 'Https'),
    (None, None, '5.2, 7.3, A6.2 y 3 A6.8, A7, A5.10, 12 a 15, 33', 'OPORTUNIDAD_MEJORA', 'Aplicación de controles en areas operativas', 'Se observan políticas de sarlaft y de sistema dentifraude mas no de seguridad de la información'),
    (None, None, '7.3 Concienciación', 'CONFORMIDAD', '7.3 Concienciación', ''),
    (None, None, 'A5.10 uso aceptable', 'CONFORMIDAD', 'A5.10 uso aceptable', ''),
    (None, None, 'A5.12 clasificación de información', 'OPORTUNIDAD_MEJORA', 'A5.12 clasificación de información', 'Usuario Manaure no conoce clasificación de información'),
    (None, None, 'A5.13 Etiquetado', 'NO_CONFORMIDAD', 'A5.13 Etiquetado', ''),
    (None, None, 'A5.14 Transferencias', 'CONFORMIDAD', 'A5.14 Transferencias', ''),
    (None, None, 'A5.15 Control de acceso', 'CONFORMIDAD', 'A5.15 Control de acceso', ''),
    (None, None, 'A5.33 Protección de registros', 'NO_CONFORMIDAD', 'A5.33 Protección de registros', 'documentos con información personal del año 2023 y 2024 en archivo sin gestión'),
    (None, None, 'A6.2 Términos y condiciones de empleo', 'CONFORMIDAD', 'A6.2 Términos y condiciones de empleo', ''),
    (None, None, 'A6.3 Conciencia', 'CONFORMIDAD', 'A6.3 Conciencia', ''),
    (None, None, 'A6.8 Informe de eventos', 'CONFORMIDAD', 'A6.8 Informe de eventos', 'Mesa de ayuda. Teléfono'),
    (None, None, 'A.7.1 Perímetros de seguridad física', 'OPORTUNIDAD_MEJORA', 'A.7.1 Perímetros de seguridad física', 'Aislamiento de areas de permanencia del público en las sedes Distracción, Barrancas, Albania.'),
    (None, None, 'A.7.2 Entrada física', 'CONFORMIDAD', 'A.7.2 Entrada física', 'puerta con cerradura, marco sin reja (Uribia)'),
    (None, None, 'A.7.3 Asegurar oficinas, habitaciones e instalaciones', 'OPORTUNIDAD_MEJORA', 'A.7.3 Asegurar oficinas, habitaciones e instalaciones', 'Implementar sistema de alarma con monitoreo y reacción con detección de movimiento, incendio. El perímetro de seguridad física de la sede Uribia tiene ventanas con rejas y puerta de vidrio sin reja y ventana de aluminio (sin reja) en el baño con acceso a zona común'),
    (None, None, 'A.7.4 Supervisión de la seguridad física', 'OPORTUNIDAD_MEJORA', 'A.7.4 Supervisión de la seguridad física', 'Implementar monitoreo de cámara en la sede de Nazareth. La pantalla de monitoreo de la sede no es visible a los funcionarios (Manaure - Uribia)'),
    (None, None, 'A.7.5 Protección contra amenazas físicas y ambientales', '', 'A.7.5 Protección contra amenazas físicas y ambientales', 'Extintores al día. Uribia tiene CO2 y ABC, Manaure solo CO2'),
    (None, None, 'A.7.6 Trabajar en áreas seguras', 'OPORTUNIDAD_MEJORA', 'A.7.6 Trabajar en áreas seguras', 'Puerta de acceso a los cubículos de atención abierta (Uribia y Manaure)'),
    (None, None, 'a5.34 protección de datos', 'FORTALEZA', 'a5.34 protección de datos', 'Aviso de videograbación en las sedes, título en wayuunaiki. Mayoría de usuarios solo hablan wayuunaiki'),
    (None, None, '', '', 'Observación de campo (visita a sedes)', 'Antivirus Manaure tiene alerta sin gestión'),
    (None, None, '', '', 'Observación de campo (visita a sedes)', 'Puerta de acceso a cubículos abierta'),
    (None, None, '', '', 'Observación de campo (visita a sedes)', 'Cerraduras de los archivadores no sirven y tienen las llaves pegadas'),
    (None, None, '', '', 'Observación de campo (visita a sedes)', 'Suministro eléctrico intermitente'),
    ('tema', 'Desarrollo y sistemas', 'A5.15, A8.3 a 5, A8.11, 26 a 32', 'CONFORMIDAD', 'Desarrollo de software', ''),
    ('tema', 'Desarrollo y sistemas', 'A8.3 Restricción de acceso a la información', 'CONFORMIDAD', 'A8.3 Restricción de acceso a la información', ''),
    ('tema', 'Desarrollo y sistemas', 'A8.4 Acceso al código fuente', 'CONFORMIDAD', 'A8.4 Acceso al código fuente', ''),
    ('tema', 'Desarrollo y sistemas', 'A8.5 Autenticación segura', 'CONFORMIDAD', 'A8.5 Autenticación segura', ''),
    ('tema', 'Desarrollo y sistemas', 'A8.11 Enmascaramiento de datos', 'CONFORMIDAD', 'A8.11 Enmascaramiento de datos', 'En contraseñas'),
    ('tema', 'Desarrollo y sistemas', 'a8.25 Ciclo de vida de desarrollo seguro', 'NO_CONFORMIDAD', 'a8.25 Ciclo de vida de desarrollo seguro', 'No existe evidencia de implementación'),
    ('tema', 'Desarrollo y sistemas', 'A8.26 Requisitos de seguridad de las aplicaciones', 'NO_CONFORMIDAD', 'A8.26 Requisitos de seguridad de las aplicaciones', 'No se evidencia documentación de requisitos'),
    ('tema', 'Desarrollo y sistemas', 'A8.27 Arquitectura de sistemas seguros y principios de ingeniería', 'CONFORMIDAD', 'A8.27 Arquitectura de sistemas seguros y principios de ingeniería', 'Política de desarrollo seguro'),
    ('tema', 'Desarrollo y sistemas', 'A8.28 Codificación segura', 'OPORTUNIDAD_MEJORA', 'A8.28 Codificación segura', 'No existe evidencia de implementación'),
    ('tema', 'Desarrollo y sistemas', 'A8.29 Pruebas de seguridad en desarrollo y aceptación', 'NO_CONFORMIDAD', 'A8.29 Pruebas de seguridad en desarrollo y aceptación', 'no se hacen pruebas (el desarrollo)'),
    ('tema', 'Desarrollo y sistemas', 'A8.30 Desarrollo externalizado', '', 'A8.30 Desarrollo externalizado', 'Proyecto: gestión de indicadores y notas técnicas.'),
    ('tema', 'Desarrollo y sistemas', 'A8.31 Separación de entornos de desarrollo, prueba y producción', 'OPORTUNIDAD_MEJORA', 'A8.31 Separación de entornos de desarrollo, prueba y producción', 'se cuenta con bases de datos separadas pero no está separado'),
    ('tema', 'Desarrollo y sistemas', 'A8.32 Gestión del cambio', 'CONFORMIDAD', 'A8.32 Gestión del cambio', ''),
    ('tema', 'Desarrollo y sistemas', 'A.8.33 Información de la prueba', 'NO_CONFORMIDAD', 'A.8.33 Información de la prueba', 'No existe evidencia de implementación'),
    ('tema', 'Desarrollo y sistemas', '', '', 'Observación de campo', 'Contraseña de GitHub en texto claro (equipo de desarrollo)'),
    ('tema', 'Seguridad física', 'A.7.1 a 6, A7.9', 'CONFORMIDAD', 'Seguridad física', ''),
    ('tema', 'Seguridad física', 'A.7.2 acceso físico', 'FORTALEZA', 'A.7.2 acceso físico', 'Maicao: externo y a zonas restringidas. Proyecto en curso cubre archivo'),
    ('tema', 'Seguridad física', 'A.7.3 asegurar recintos', 'CONFORMIDAD', 'A.7.3 asegurar recintos', ''),
    ('tema', 'Seguridad física', 'A.7.4 monitoreo', 'FORTALEZA', 'A.7.4 monitoreo', 'Externo, interno sin monitoreo constante. Falta sede Nazareth'),
    ('tema', 'Seguridad física', 'A.7.5 protección contra amenazas físicas', 'OPORTUNIDAD_MEJORA', 'A.7.5 protección contra amenazas físicas', 'extintor de archivo no está en la ubicación, no hay sensores, alarmas en archivo'),
    ('tema', 'Seguridad física', 'A.7.6 Trabajo en áreas seguras', 'CONFORMIDAD', 'A.7.6 Trabajo en áreas seguras', 'No existen disposiciones diferenciadas para trabajo en zonas seguras'),
    ('tema', 'Seguridad física', 'A.7.8 Emplazamiento y protección de equipos', 'OPORTUNIDAD_MEJORA', 'A.7.8 Emplazamiento y protección de equipos', 'DVR locales en sedes, equipos de red satelital y seguridad fuera de rack'),
    ('tema', 'Seguridad física', 'A5.33 protección de registros', 'NO_CONFORMIDAD', 'A5.33 protección de registros', 'Archivo: Documentos en el piso, humedad, almacenamiento de materiales y partes que pueden afectar los registros.'),
    ('tema', 'Gestión de Incidentes', 'A.5.5, 6, A5 24 a 28, A8.7, 15 a 17', 'CONFORMIDAD', 'Gestión de incidentes', 'CSIRT, cai virtual'),
    ('tema', 'Gestión de Incidentes', 'A5.6 contacto grupos', 'CONFORMIDAD', 'A5.6 contacto grupos', 'No existe una relación formal'),
    ('tema', 'Gestión de Incidentes', 'A5.24 planif incidentes', 'NO_CONFORMIDAD', 'A5.24 planif incidentes', 'Establecido en la Guía de gestión y clasificación de incidentes. Matriz de eventos e incidentes vacía. NO IMPLEMENTADO'),
    ('tema', 'Gestión de Incidentes', 'A5.25 evaluación y decisión', 'NO_CONFORMIDAD', 'A5.25 evaluación y decisión', 'Establecido en la guía'),
    ('tema', 'Gestión de Incidentes', 'A5.26 respuesta', 'NO_CONFORMIDAD', 'A5.26 respuesta', 'Establecido en la guía'),
    ('tema', 'Gestión de Incidentes', 'A5.27 aprendizaje incidentes', 'NO_CONFORMIDAD', 'A5.27 aprendizaje incidentes', 'Establecido en la guía'),
    ('tema', 'Gestión de Incidentes', 'A5.28 recopilación de pruebas', 'NO_CONFORMIDAD', 'A5.28 recopilación de pruebas', 'Establecido en la guía'),
    ('tema', 'Gestión de Incidentes', 'A8.7 malware', 'CONFORMIDAD', 'A8.7 malware', 'Sophos'),
    ('tema', 'Gestión de Incidentes', 'A8.15 logs', 'NO_CONFORMIDAD', 'A8.15 logs', 'Firewall sin logs habilitados. No existe disposición al respecto'),
    ('tema', 'Gestión de Incidentes', 'A8.16 monitoreo', 'NO_CONFORMIDAD', 'A8.16 monitoreo', 'No se cuenta con un sistema de monitoreo que cubra todos los activos'),
    ('tema', 'Gestión de Incidentes', 'A8.17 relojes', 'OPORTUNIDAD_MEJORA', 'A8.17 relojes', 'Reloj sincronizado en Windows y teléfonos fijos. No inalámbrico de desarrollo, no acceso a gerencia'),
    ('tema', 'Gestión de continuidad de la TI', 'A5.29, 30, A8.13, 14', 'CONFORMIDAD', 'Continuidad de la TI', 'Política de Gestión de Continuidad de la Seguridad de la Información.'),
    ('tema', 'Gestión de continuidad de la TI', 'A5.30 preparación de las TIC para la continuidad', 'NO_CONFORMIDAD', 'A5.30 preparación de las TIC para la continuidad', 'Política de Gestión de Continuidad de la Seguridad de la Información. Plantas, UPS. No existe evidencia de la planificación y realización de pruebas'),
    ('tema', 'Gestión de continuidad de la TI', 'A8.13 backup', 'OPORTUNIDAD_MEJORA', 'A8.13 backup', 'Réplicas de la BD del sistema de información. Copia del AD, firewall, routers, logs críticos. Se recomienda elaborar un plan de respaldos'),
    ('tema', 'Gestión de continuidad de la TI', 'A8.14 redundancia', 'CONFORMIDAD', 'A8.14 redundancia', 'Canales satelitales de respaldo, suplencia energía'),
    ('tema', 'Seguimiento y evaluación', '9.1, 9.2, 10.2, A5.35, 36 A8.34', 'NO_CONFORMIDAD', 'Seguimiento', 'Modelo de seguimiento y medición. Indicadores sin medición'),
    ('tema', 'Seguimiento y evaluación', '9.2 auditoría interna', 'CONFORMIDAD', '9.2 auditoría interna', 'Programa de auditoría 2025'),
    ('tema', 'Seguimiento y evaluación', '10.2 No conformidad', 'OPORTUNIDAD_MEJORA', '10.2 No conformidad', 'Procedimiento de mejora. En implementación'),
    ('tema', 'Seguimiento y evaluación', 'A5.35 Revisión independiente de la seguridad de la información', 'CONFORMIDAD', 'A5.35 Revisión independiente de la seguridad de la información', 'Hacking ético'),
    ('tema', 'Seguimiento y evaluación', 'A5.36 Cumplimiento de políticas, reglas y estándares de seguridad de la información', 'OPORTUNIDAD_MEJORA', 'A5.36 Cumplimiento de políticas, reglas y estándares de seguridad de la información', 'En implementación'),
    ('tema', 'Seguimiento y evaluación', 'A8.34 Protección de los sistemas de información durante las pruebas de auditoría', 'OPORTUNIDAD_MEJORA', 'A8.34 Protección de los sistemas de información durante las pruebas de auditoría', 'En implementación'),
    ('tema', 'Revisión por la dirección, mejora', '9.3,10.1', 'NO_CONFORMIDAD', 'Revisión por la dirección y mejora', 'No se ha realizado'),
    ('tema', 'Revisión por la dirección, mejora', '10.1 Mejora', 'OPORTUNIDAD_MEJORA', '10.1 Mejora', 'No existe evidencia de implementación'),
]

MAPA_TIPO_A_CODIGO = {
    'FORTALEZA': 'FORT',
    'OPORTUNIDAD_MEJORA': 'AM',
    'NO_CONFORMIDAD': 'NC',
}


def sembrar(apps, schema_editor):
    Empleado = apps.get_model('accounts', 'Empleado')
    Proceso = apps.get_model('activos', 'Proceso')
    Auditoria = apps.get_model('auditorias', 'Auditoria')
    Hallazgo = apps.get_model('auditorias', 'Hallazgo')
    TipoHallazgo = apps.get_model('auditorias', 'TipoHallazgo')
    SesionAuditoria = apps.get_model('auditorias', 'SesionAuditoria')
    ItemVerificacionAuditoria = apps.get_model('auditorias', 'ItemVerificacionAuditoria')

    auditoria = Auditoria.objects.filter(codigo=CODIGO_AUDITORIA).first()
    if not auditoria or auditoria.hallazgos.exists():
        return  # ya migrado, o la auditoría base (0014) no existe todavía

    auditoria.alcance = (auditoria.alcance or '') + NOTA_ALCANCE
    auditoria.fecha_elaboracion_informe = FECHA_ELABORACION_INFORME
    auditoria.conclusiones_generales = CONCLUSIONES_GENERALES
    auditoria.save(update_fields=['alcance', 'fecha_elaboracion_informe', 'conclusiones_generales'])

    gestion_humana = Proceso.objects.filter(nombre='Gestión Humana').first()
    proceso_por_bloque = {'Seguridad en el talento humano': gestion_humana}

    tipos_por_codigo = {t.codigo: t for t in TipoHallazgo.objects.filter(codigo__in=['FORT', 'AM', 'NC'])}

    def crear_hallazgos(descripciones, codigo_tipo, proceso, evidencia=''):
        tipo = tipos_por_codigo.get(codigo_tipo)
        for descripcion in descripciones:
            hallazgo = Hallazgo(
                fecha_deteccion=auditoria.fecha_auditoria,
                descripcion=descripcion,
                evidencia_asociada=evidencia,
                auditoria=auditoria,
            )
            # codigo se autogenera en el save() real del modelo, pero aquí estamos
            # usando el modelo histórico de la migración (apps.get_model), que no
            # ejecuta la lógica custom de Hallazgo.save() — se replica aquí.
            if not hallazgo.codigo:
                max_num = 0
                ancho = 3
                for codigo_existente in Hallazgo.objects.values_list('codigo', flat=True):
                    numero = codigo_existente.rsplit('-', 1)[-1]
                    if numero.isdigit():
                        max_num = max(max_num, int(numero))
                        ancho = max(ancho, len(numero))
                hallazgo.codigo = f'H-{str(max_num + 1).zfill(ancho)}'
            hallazgo.save()
            if tipo:
                hallazgo.tipos.add(tipo)
            if proceso:
                hallazgo.procesos.add(proceso)

    for proceso_nombre, responsable, fortalezas, aspectos, no_conformidades, ac_aspectos, ac_nc in BLOQUES_INFORME:
        proceso_fk = proceso_por_bloque.get(proceso_nombre)
        crear_hallazgos(fortalezas, 'FORT', proceso_fk)
        evidencia_aspectos = f'Responsable del proceso: {responsable}.' + (f' Acción correctiva sugerida por el auditor: {ac_aspectos}' if ac_aspectos else '')
        crear_hallazgos(aspectos, 'AM', proceso_fk, evidencia=evidencia_aspectos)
        evidencia_nc = f'Responsable del proceso: {responsable}.' + (f' Acción correctiva sugerida por el auditor: {ac_nc}' if ac_nc else '')
        crear_hallazgos(no_conformidades, 'NC', proceso_fk, evidencia=evidencia_nc)

    sesiones_por_tema = {s.tema: s for s in auditoria.sesiones.all() if s.tema}
    sesiones_por_proceso = {s.proceso.nombre: s for s in auditoria.sesiones.select_related('proceso').all() if s.proceso_id}

    for clave_tipo, clave_valor, requisito_iso, tipo, desc_elemento, desc_hallazgo in ITEMS_CHECKLIST:
        sesion = None
        if clave_tipo == 'tema':
            sesion = sesiones_por_tema.get(clave_valor)
        elif clave_tipo == 'proceso':
            sesion = sesiones_por_proceso.get(clave_valor)
        ItemVerificacionAuditoria.objects.create(
            auditoria=auditoria,
            sesion=sesion,
            etapa='',
            descripcion_elemento=desc_elemento,
            requisito_iso=requisito_iso,
            otros_requisitos='',
            tipo_hallazgo=tipo,
            descripcion_hallazgo=desc_hallazgo,
        )


def deshacer(apps, schema_editor):
    Auditoria = apps.get_model('auditorias', 'Auditoria')
    Hallazgo = apps.get_model('auditorias', 'Hallazgo')
    ItemVerificacionAuditoria = apps.get_model('auditorias', 'ItemVerificacionAuditoria')

    auditoria = Auditoria.objects.filter(codigo=CODIGO_AUDITORIA).first()
    if not auditoria:
        return
    Hallazgo.objects.filter(auditoria=auditoria).delete()
    ItemVerificacionAuditoria.objects.filter(auditoria=auditoria).delete()
    auditoria.conclusiones_generales = (
        'Auditoría realizada por un auditor externo (Mauricio Mantilla Álvarez) del '
        '9 al 11 de diciembre de 2025. Solo se cargó el Plan de Auditoría (FO-860-24).'
    )
    auditoria.fecha_elaboracion_informe = None
    auditoria.save(update_fields=['conclusiones_generales', 'fecha_elaboracion_informe'])


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0014_seed_auditoria_2025_realizada'),
    ]

    operations = [
        migrations.RunPython(sembrar, deshacer),
    ]
