# Generated by Django 6.1 on 2026-09-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_revisionsemestralactivos_snapshotactivo'),
        ('auditorias', '0015_seed_informe_y_checklist_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallazgo',
            name='tema',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tema / dominio del hallazgo'),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='procesos',
            field=models.ManyToManyField(blank=True, db_table='hallazgoProcesos', related_name='hallazgos', to='activos.proceso', verbose_name='Proceso'),
        ),
    ]
