# -*- coding: utf-8 -*-
# Generated by Django 6.1 on 2026-09-22 22:40

from django.db import migrations

CODIGO_AUDITORIA = 'AUD-2025-001'

# Réplica del orden exacto en que la migración 0015 creó los Hallazgo (por bloque del
# informe: primero sus Fortalezas, luego sus Aspectos por mejorar, luego sus No
# conformidades) — permite backfillear Hallazgo.tema (agregado en la migración 0016,
# después de que estos 40 hallazgos ya existían) sin tener que repetir aquí todo el
# texto de BLOQUES_INFORME otra vez.
# (proceso_o_tema, n_fortalezas, n_aspectos, n_no_conformidades)
CONTEOS_POR_BLOQUE = [
    ('Planificación del SGSI', 2, 2, 2),
    ('Gestión de riesgos de SI', 1, 1, 2),
    ('Seguridad en el talento humano', 2, 1, 1),
    ('Seguridad en procesos y servicios tercerizados', 2, 1, 1),
    ('Infraestructura TI', 1, 1, 1),
    ('Aplicación de controles en areas operativas', 1, 3, 2),
    ('Desarrollo de software', 1, 1, 1),
    ('Seguridad física', 1, 0, 1),
    ('Gestión de incidentes', 1, 0, 2),
    ('Continuidad de la TI', 2, 0, 1),
    ('Seguimiento y evaluación del SGSI', 0, 1, 0),
    ('Revisión por la dirección y mejora', 0, 0, 1),
]


def sembrar(apps, schema_editor):
    Auditoria = apps.get_model('auditorias', 'Auditoria')
    Hallazgo = apps.get_model('auditorias', 'Hallazgo')

    auditoria = Auditoria.objects.filter(codigo=CODIGO_AUDITORIA).first()
    if not auditoria:
        return

    ids = list(Hallazgo.objects.filter(auditoria=auditoria).order_by('id').values_list('id', flat=True))
    total_esperado = sum(f + a + n for _, f, a, n in CONTEOS_POR_BLOQUE)
    if len(ids) != total_esperado:
        return  # datos ya distintos a lo esperado (ej. migración ya corrida o hallazgos editados a mano)

    cursor = 0
    for tema, n_f, n_a, n_n in CONTEOS_POR_BLOQUE:
        cantidad = n_f + n_a + n_n
        ids_bloque = ids[cursor:cursor + cantidad]
        cursor += cantidad
        Hallazgo.objects.filter(id__in=ids_bloque, tema='').update(tema=tema)


def deshacer(apps, schema_editor):
    Auditoria = apps.get_model('auditorias', 'Auditoria')
    Hallazgo = apps.get_model('auditorias', 'Hallazgo')
    auditoria = Auditoria.objects.filter(codigo=CODIGO_AUDITORIA).first()
    if auditoria:
        Hallazgo.objects.filter(auditoria=auditoria).update(tema='')


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0016_hallazgo_tema_alter_hallazgo_procesos'),
    ]

    operations = [
        migrations.RunPython(sembrar, deshacer),
    ]
