# -*- coding: utf-8 -*-
# Generated by Django 6.1 on 2026-09-22 23:05

from django.db import migrations

CODIGO_AUDITORIA = 'AUD-2025-001'


def sembrar(apps, schema_editor):
    Auditoria = apps.get_model('auditorias', 'Auditoria')
    ProgramaAuditoria = apps.get_model('auditorias', 'ProgramaAuditoria')

    auditoria = Auditoria.objects.filter(codigo=CODIGO_AUDITORIA).first()
    if not auditoria or auditoria.programa_id:
        return

    # No se liga a un solo Proceso del catálogo: fue una auditoría general del SGSI
    # (12 temas/dominios distintos, ver migración 0015), no específica de un proceso
    # — mismo criterio que el real FO-860-23 usa para "Auditoria Interna SGSI Sede
    # Principal" (servicio_o_proyecto='SGSI', sin proceso puntual). Fechas puestas a
    # ojo (diciembre 2025, cuando ocurrió de verdad) — el usuario dijo que las
    # ajustaría después.
    programa = ProgramaAuditoria.objects.create(
        anio=2025,
        tipo='INTERNA',
        proceso=None,
        auditado='',
        procedimiento='Auditoría Interna SGSI',
        servicio_o_proyecto='SGSI',
        auditor_lider=auditoria.auditor_lider,
        mes_planeado=12,
    )
    auditoria.programa = programa
    auditoria.save(update_fields=['programa'])


def deshacer(apps, schema_editor):
    Auditoria = apps.get_model('auditorias', 'Auditoria')
    ProgramaAuditoria = apps.get_model('auditorias', 'ProgramaAuditoria')

    auditoria = Auditoria.objects.filter(codigo=CODIGO_AUDITORIA).first()
    if auditoria and auditoria.programa_id:
        programa = auditoria.programa
        auditoria.programa = None
        auditoria.save(update_fields=['programa'])
        programa.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0017_backfill_tema_hallazgos_2025'),
    ]

    operations = [
        migrations.RunPython(sembrar, deshacer),
    ]
