# -*- coding: utf-8 -*-
# Generated by Django 6.1 on 2026-09-23 12:00

from django.db import migrations

# Al cargar los 40 hallazgos reales del Informe de diciembre 2025 (migración 0015) se
# generaron 5 duplicados exactos de hallazgos que el equipo ya había registrado (y
# venía gestionando) ANTES de esa carga — el usuario los detectó al abrir H-001 en el
# módulo de Hallazgos y notar que no tenía el campo nuevo de items relacionados (ver
# ESTADO_PROYECTO.md, sección "Hallazgos ↔ Lista de verificación").
#
# Se decidió (con el usuario, vía pregunta directa): conservar los hallazgos VIEJOS
# (ya tienen seguimiento real: 1 a 3 gestiones cada uno, estado CERRADA), vincularlos
# a AUD-2025-001, y eliminar los 5 NUEVOS (sin ningún seguimiento todavía) para no
# perder el historial de remediación ya hecho.
#
# (código_viejo_a_conservar, código_nuevo_a_eliminar)
PARES_DUPLICADOS = [
    ('H-001', 'H-030'),
    ('H-002', 'H-043'),
    ('H-005', 'H-040'),
    ('H-007', 'H-052'),
    ('H-014', 'H-056'),
]


def resolver(apps, schema_editor):
    Hallazgo = apps.get_model('auditorias', 'Hallazgo')

    for codigo_viejo, codigo_nuevo in PARES_DUPLICADOS:
        viejo = Hallazgo.objects.filter(codigo=codigo_viejo).first()
        nuevo = Hallazgo.objects.filter(codigo=codigo_nuevo).first()
        if not viejo or not nuevo:
            continue  # ya se resolvió a mano, o los códigos cambiaron
        if viejo.auditoria_id != nuevo.auditoria_id:
            viejo.auditoria_id = nuevo.auditoria_id
            viejo.save(update_fields=['auditoria'])
        nuevo.delete()


def deshacer(apps, schema_editor):
    # No reversible de forma segura (el hallazgo "nuevo" eliminado no se puede
    # reconstruir con fidelidad) — no se intenta.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0018_programa_para_auditoria_2025'),
    ]

    operations = [
        migrations.RunPython(resolver, deshacer),
    ]
