# -*- coding: utf-8 -*-
# Generated by Django 6.1 on 2026-09-23 13:00

from django.db import migrations

# El usuario pidió revertir la carga masiva de hallazgos desde el Informe de
# auditoría (migración 0015): quiere que el módulo de Hallazgos vuelva a tener SOLO
# los hallazgos que ya existían antes de esta sesión, y relacionarlos él mismo, a
# mano, con los items de la Lista de Verificación de AUD-2025-001 desde una nueva
# columna en el módulo de Hallazgos (organizado por año) — no quiere que la carga
# masiva automática siga viviendo como registros de Hallazgo.
#
# No se toca la Auditoria en sí, ni su Plan, Cronograma ni los 119
# ItemVerificacionAuditoria (la Lista de Verificación real sigue intacta) — solo se
# revierte lo que se había creado en el módulo de Hallazgos a partir de ella.
#
# Los 5 hallazgos que ya existían y se habían fusionado con sus duplicados nuevos
# (migración 0019: H-001, H-002, H-005, H-007, H-014) se conservan tal cual estaban
# ANTES de esa fusión — se les quita el auditoria_id que se les había puesto, para
# que el usuario los relacione él mismo con la columna nueva.
CODIGO_AUDITORIA = 'AUD-2025-001'
CODIGOS_A_DESVINCULAR_NO_BORRAR = ['H-001', 'H-002', 'H-005', 'H-007', 'H-014']


def revertir(apps, schema_editor):
    Auditoria = apps.get_model('auditorias', 'Auditoria')
    Hallazgo = apps.get_model('auditorias', 'Hallazgo')

    auditoria = Auditoria.objects.filter(codigo=CODIGO_AUDITORIA).first()
    if not auditoria:
        return

    Hallazgo.objects.filter(auditoria=auditoria, codigo__in=CODIGOS_A_DESVINCULAR_NO_BORRAR).update(auditoria=None)
    Hallazgo.objects.filter(auditoria=auditoria).exclude(codigo__in=CODIGOS_A_DESVINCULAR_NO_BORRAR).delete()


def restaurar(apps, schema_editor):
    # No reversible con fidelidad (los hallazgos borrados no se pueden reconstruir
    # aquí sin repetir todo el texto de la migración 0015) — no se intenta.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0019_resolver_duplicados_hallazgos_2025'),
    ]

    operations = [
        migrations.RunPython(revertir, restaurar),
    ]
