# -*- coding: utf-8 -*-
# Generated by Django 6.1 on 2026-09-24 10:00

from django.db import migrations

# El usuario detectó (comparando contra el Excel real FO-860-25) que la Lista de
# Verificación de AUD-2025-001 (sembrada en la migración 0015) no respetó la
# estructura real del documento: en el Excel, la columna "Descripción del elemento a
# revisar" usa celdas combinadas cuando un mismo tema (ej. "Contexto", "Liderazgo",
# "Infraestructura TI") tiene varias filas de evaluación debajo — pero la extracción
# original, al toparse con esas celdas combinadas (vacías salvo en la primera fila del
# grupo), tomó por error el valor de la columna "Otros Requisito" (J) de esa fila como
# si fuera un elemento nuevo. Por eso "Requisitos legales A.5.31", "5.2", "A5.3", etc.
# aparecían como si fueran "elementos a revisar" propios en vez de quedar agrupados
# bajo su tema real.
#
# Se releyó el archivo real (Auditoria/9.2 auditoria interna/Auditoria Interna
# realizada 2025/FO-860-25-...xlsx, no versionado en git) respetando sus celdas
# combinadas D:H por hoja (una hoja = una sesión/tema), y se comparó fila por fila
# contra el orden exacto de creación de ITEMS_CHECKLIST en la migración 0015 (usando
# tipo_hallazgo + descripcion_hallazgo como huella para verificar la alineación
# posicional antes de confiar en la corrección — los 119 items de ambas fuentes
# coincidieron 1 a 1 sin ambigüedad).
#
# Dentro de varios de esos grupos, el propio Excel deja la celda de "elemento a
# revisar" en blanco para las filas siguientes a la primera (el auditor no repitió el
# encabezado para cada control individual) — se decidió heredar (forward-fill) el
# último encabezado no vacío dentro de la misma hoja en vez de dejar el campo vacío,
# para cumplir lo pedido explícitamente por el usuario ("si evaluaron varios aspectos
# del contexto, quede dentro del mismo"). Los encabezados heredados coinciden
# exactamente con los 12 nombres de proceso del Informe real (FO-860-22), lo que
# corrobora que la agrupación es correcta.
#
# No se toca ningún otro campo (requisito_iso, tipo_hallazgo, descripcion_hallazgo,
# sesion, hallazgo_generado) — varios de estos items ya están vinculados a hallazgos
# reales (H-001, H-002, H-003) y esos vínculos no se alteran.
#
# (id, descripcion_elemento_correcta)
CORRECCIONES = [
    (3, 'Contexto'),
    (4, 'Contexto'),
    (6, 'Liderazgo'),
    (13, 'Roles y responsabilidades'),
    (15, 'Gestión de riesgos de seguridad de la información'),
    (16, 'Gestión de riesgos de seguridad de la información'),
    (17, 'Gestión de riesgos de seguridad de la información'),
    (18, 'Gestión de riesgos de seguridad de la información'),
    (19, 'Gestión de riesgos de seguridad de la información'),
    (20, 'Gestión de riesgos de seguridad de la información'),
    (22, 'Seguridad en Gestión Humana'),
    (23, 'Seguridad en Gestión Humana'),
    (24, 'Seguridad en Gestión Humana'),
    (25, 'Seguridad en Gestión Humana'),
    (26, 'Seguridad en Gestión Humana'),
    (27, 'Seguridad en Gestión Humana'),
    (28, 'Seguridad en Gestión Humana'),
    (29, 'Seguridad en Gestión Humana'),
    (30, 'Seguridad en Gestión Humana'),
    (31, 'Seguridad en Gestión Humana'),
    (33, 'Seguridad en procesos y servicios tercerizados'),
    (34, 'Seguridad en procesos y servicios tercerizados'),
    (35, 'Seguridad en procesos y servicios tercerizados'),
    (36, 'Seguridad en procesos y servicios tercerizados'),
    (37, 'Seguridad en procesos y servicios tercerizados'),
    (39, 'Infraestructura TI'),
    (40, 'Infraestructura TI'),
    (41, 'Infraestructura TI'),
    (42, 'Infraestructura TI'),
    (43, 'Infraestructura TI'),
    (44, 'Infraestructura TI'),
    (45, 'Infraestructura TI'),
    (46, 'Infraestructura TI'),
    (47, 'Infraestructura TI'),
    (48, 'Infraestructura TI'),
    (49, 'Infraestructura TI'),
    (50, 'Infraestructura TI'),
    (51, 'Infraestructura TI'),
    (52, 'Infraestructura TI'),
    (54, 'Aplicación de controles en areas operativas'),
    (55, 'Aplicación de controles en areas operativas'),
    (56, 'Aplicación de controles en areas operativas'),
    (57, 'Aplicación de controles en areas operativas'),
    (58, 'Aplicación de controles en areas operativas'),
    (59, 'Aplicación de controles en areas operativas'),
    (60, 'Aplicación de controles en areas operativas'),
    (61, 'Aplicación de controles en areas operativas'),
    (62, 'Aplicación de controles en areas operativas'),
    (63, 'Aplicación de controles en areas operativas'),
    (64, 'Aplicación de controles en areas operativas'),
    (65, 'Aplicación de controles en areas operativas'),
    (66, 'Aplicación de controles en areas operativas'),
    (67, 'Aplicación de controles en areas operativas'),
    (68, 'Aplicación de controles en areas operativas'),
    (69, 'Aplicación de controles en areas operativas'),
    (70, 'Aplicación de controles en areas operativas'),
    (76, 'Desarrollo de software'),
    (77, 'Desarrollo de software'),
    (78, 'Desarrollo de software'),
    (79, 'Desarrollo de software'),
    (80, 'Desarrollo de software'),
    (81, 'Desarrollo de software'),
    (82, 'Desarrollo de software'),
    (83, 'Desarrollo de software'),
    (84, 'Desarrollo de software'),
    (85, 'Desarrollo de software'),
    (86, 'Desarrollo de software'),
    (87, 'Desarrollo de software'),
    (88, 'Desarrollo de software'),
    (91, 'Seguridad física'),
    (92, 'Seguridad física'),
    (93, 'Seguridad física'),
    (94, 'Seguridad física'),
    (95, 'Seguridad física'),
    (96, 'Seguridad física'),
    (97, 'Seguridad física'),
    (99, 'Gestión de incidentes'),
    (100, 'Gestión de incidentes'),
    (101, 'Gestión de incidentes'),
    (102, 'Gestión de incidentes'),
    (103, 'Gestión de incidentes'),
    (104, 'Gestión de incidentes'),
    (105, 'Gestión de incidentes'),
    (106, 'Gestión de incidentes'),
    (107, 'Gestión de incidentes'),
    (108, 'Gestión de incidentes'),
    (110, 'Continuidad de la TI'),
    (111, 'Continuidad de la TI'),
    (112, 'Continuidad de la TI'),
    (114, 'Seguimiento'),
    (115, 'Seguimiento'),
    (116, 'Seguimiento'),
    (117, 'Seguimiento'),
    (118, 'Seguimiento'),
    (120, 'Revisión por la dirección y mejora'),
]

# (id, descripcion_elemento_anterior) — para poder deshacer con fidelidad.
VALORES_ANTERIORES = [
    (3, 'Requisitos legales A.5.31'),
    (4, '8.1 A5.1 a 4,34,37'),
    (6, '5.2'),
    (13, 'A5.3'),
    (15, '6.1.2, 8.2'),
    (16, '6.1.3, 8.3'),
    (17, '6.1.3, 8.3'),
    (18, 'A5.7'),
    (19, 'A5.8'),
    (20, 'A5.9'),
    (22, '7.2'),
    (23, '7.3'),
    (24, 'A5.2'),
    (25, 'A5.3'),
    (26, 'A6.1'),
    (27, 'A6.2'),
    (28, 'A6.3'),
    (29, 'A6.4'),
    (30, 'A6.5'),
    (31, 'A6.6'),
    (33, 'A5.19 Seguridad de la información en las relaciones con el proveedor'),
    (34, 'A5.20 Abordar la seguridad de la información dentro de los acuerdos con proveedores'),
    (35, 'A5.21 Gestión de la seguridad de la información en la cadena de suministro de la tecnología de la información y la comunicación (TIC)'),
    (36, 'A5.22 Seguimiento, revisión y gestión del cambio de los servicios de los proveedores'),
    (37, 'A5.23 Seguridad de la información para el uso de servicios en la nube'),
    (39, 'a7.13 mtto de equipos'),
    (40, 'a8.2 acceso privilegiado'),
    (41, 'a8.6 capacidad'),
    (42, 'a 8.8. vulnerabilidad tecnica'),
    (43, 'a8.9 gestion de configuración'),
    (44, 'a8,12 fuga'),
    (45, 'a8 13 copias'),
    (46, 'a8.18 Uso de programas de utilidad privilegiados'),
    (47, 'a8.19 Instalación de software en sistemas operativos'),
    (48, 'a8.20 Seguridad de redes'),
    (49, 'a8.21 Seguridad de los servicios de red'),
    (50, 'a8.22 Segregación de redes'),
    (51, 'a8.23 Filtrado web'),
    (52, 'a8.24 Uso de la criptografía'),
    (54, '7.3 Concienciación'),
    (55, 'A5.10 uso aceptable'),
    (56, 'A5.12 clasificación de información'),
    (57, 'A5.13 Etiquetado'),
    (58, 'A5.14 Transferencias'),
    (59, 'A5.15 Control de acceso'),
    (60, 'A5.33 Protección de registros'),
    (61, 'A6.2 Términos y condiciones de empleo'),
    (62, 'A6.3 Conciencia'),
    (63, 'A6.8 Informe de eventos'),
    (64, 'A.7.1 Perímetros de seguridad física'),
    (65, 'A.7.2 Entrada física'),
    (66, 'A.7.3 Asegurar oficinas, habitaciones e instalaciones'),
    (67, 'A.7.4 Supervisión de la seguridad física'),
    (68, 'A.7.5 Protección contra amenazas físicas y ambientales'),
    (69, 'A.7.6 Trabajar en áreas seguras'),
    (70, 'a5.34 protección de datos'),
    (76, 'A8.3 Restricción de acceso a la información'),
    (77, 'A8.4 Acceso al código fuente'),
    (78, 'A8.5 Autenticación segura'),
    (79, 'A8.11 Enmascaramiento de datos'),
    (80, 'a8.25 Ciclo de vida de desarrollo seguro'),
    (81, 'A8.26 Requisitos de seguridad de las aplicaciones'),
    (82, 'A8.27 Arquitectura de sistemas seguros y principios de ingeniería'),
    (83, 'A8.28 Codificación segura'),
    (84, 'A8.29 Pruebas de seguridad en desarrollo y aceptación'),
    (85, 'A8.30 Desarrollo externalizado'),
    (86, 'A8.31 Separación de entornos de desarrollo, prueba y producción'),
    (87, 'A8.32 Gestión del cambio'),
    (88, 'A.8.33 Información de la prueba'),
    (91, 'A.7.2 acceso físico'),
    (92, 'A.7.3 asegurar recintos'),
    (93, 'A.7.4 monitoreo'),
    (94, 'A.7.5 protección contra amenazas físicas'),
    (95, 'A.7.6 Trabajo en áreas seguras'),
    (96, 'A.7.8 Emplazamiento y protección de equipos'),
    (97, 'A5.33 protección de registros'),
    (99, 'A5.6 contacto grupos'),
    (100, 'A5.24 planif incidentes'),
    (101, 'A5.25 evaluación y decisión'),
    (102, 'A5.26 respuesta'),
    (103, 'A5.27 aprendizaje incidentes'),
    (104, 'A5.28 recopilación de pruebas'),
    (105, 'A8.7 malware'),
    (106, 'A8.15 logs'),
    (107, 'A8.16 monitoreo'),
    (108, 'A8.17 relojes'),
    (110, 'A5.30 preparación de las TIC para la continuidad'),
    (111, 'A8.13 backup'),
    (112, 'A8.14 redundancia'),
    (114, '9.2 auditoría interna'),
    (115, '10.2 No conformidad'),
    (116, 'A5.35 Revisión independiente de la seguridad de la información'),
    (117, 'A5.36 Cumplimiento de políticas, reglas y estándares de seguridad de la información'),
    (118, 'A8.34 Protección de los sistemas de información durante las pruebas de auditoría'),
    (120, '10.1 Mejora'),
]


def aplicar(mapa):
    def _run(apps, schema_editor):
        ItemVerificacionAuditoria = apps.get_model('auditorias', 'ItemVerificacionAuditoria')
        for item_id, valor in mapa:
            ItemVerificacionAuditoria.objects.filter(id=item_id).update(descripcion_elemento=valor)
    return _run


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0020_revertir_hallazgos_masivos_2025'),
    ]

    operations = [
        migrations.RunPython(aplicar(CORRECCIONES), aplicar(VALORES_ANTERIORES)),
    ]
