# Generated by Django 6.1 on 2026-08-14 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'proceso',
                'verbose_name_plural': 'procesos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_activo', models.CharField(choices=[('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario')], max_length=15)),
                ('clase_activo', models.CharField(choices=[('INFORMACION', 'Información'), ('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('SERVICIO', 'Servicio'), ('PERSONAS', 'Personas'), ('INSTALACIONES', 'Instalaciones')], max_length=20)),
                ('naturaleza', models.CharField(choices=[('FISICO', 'Físico'), ('DIGITAL', 'Digital'), ('SERVICIO', 'Como servicio')], max_length=15)),
                ('etiquetado', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('CONFIDENCIAL', 'Confidencial')], default='PRIVADO', max_length=15)),
                ('contiene_datos_personales', models.BooleanField(default=False, verbose_name='¿Contiene datos personales? (Ley 1581 de 2012)')),
                ('valor_confidencialidad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=5)),
                ('valor_integridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=5)),
                ('valor_disponibilidad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=5)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=20)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('custodio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_custodiados', to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_propios', to=settings.AUTH_USER_MODEL)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.direccion')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.proceso')),
            ],
            options={
                'verbose_name': 'activo',
                'verbose_name_plural': 'activos',
                'ordering': ['codigo'],
            },
        ),
    ]
