# Generated by Django 6.1 on 2026-08-18 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='clase_activo',
            field=models.CharField(choices=[('INFORMACION', 'Información'), ('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('SERVICIO', 'Servicio'), ('PERSONAS', 'Personas'), ('INSTALACIONES', 'Instalaciones')], max_length=20, verbose_name='Clase de Activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='contiene_datos_personales',
            field=models.BooleanField(default=False, verbose_name='¿El activo contiene datos personales (Ley 1581 de 2012)? LEY DATOS PERSONALES'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='custodio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_custodiados', to=settings.AUTH_USER_MODEL, verbose_name='Custodio del Activo de Información'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción del activo de información'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.direccion', verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='etiquetado',
            field=models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('CONFIDENCIAL', 'Confidencial')], default='PRIVADO', max_length=15, verbose_name='Etiquetado de la Información'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='naturaleza',
            field=models.CharField(choices=[('FISICO', 'Físico'), ('DIGITAL', 'Digital'), ('SERVICIO', 'Como servicio')], max_length=15, verbose_name='Físico / Digital / Como servicio'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Activo de Información'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.proceso', verbose_name='Proceso'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_propios', to=settings.AUTH_USER_MODEL, verbose_name='Propietario del activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='tipo_activo',
            field=models.CharField(choices=[('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario')], max_length=15, verbose_name='Tipo de Activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='valor_confidencialidad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=5, verbose_name='Confidencialidad'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='valor_disponibilidad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=5, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='valor_integridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=5, verbose_name='Integridad'),
        ),
    ]
