# Generated by Django 6.1 on 2026-08-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_alter_activo_clase_activo_alter_activo_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='naturaleza',
            field=models.CharField(choices=[('FISICO', 'Fisico'), ('DIGITAL', 'Digital'), ('SAAS', 'SaaS'), ('IAAS', 'IaaS'), ('PAAS', 'PaaS')], max_length=15, verbose_name='Físico / Digital / Como servicio'),
        ),
    ]
