# Generated by Django 6.1 on 2026-08-19 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_alter_activo_naturaleza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'ordering': ['proceso__nombre', 'nombre'], 'verbose_name': 'dirección', 'verbose_name_plural': 'direcciones'},
        ),
        migrations.AddField(
            model_name='direccion',
            name='proceso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to='activos.proceso', verbose_name='Proceso'),
            preserve_default=False,
        ),
    ]
