# Generated by Django 6.1 on 2026-08-19 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_alter_direccion_options_direccion_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to='activos.proceso', verbose_name='Proceso'),
        ),
    ]
