# Generated by Django 6.1 on 2026-08-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_direccion_codigo_alter_direccion_proceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='proceso',
        ),
    ]
