# Generated by Django 6.1 on 2026-08-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_remove_activo_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='clase_activo',
            field=models.CharField(choices=[('SISTEMAS_INFORMACION', 'Sistemas de Información'), ('PERSONAL', 'Personal'), ('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('INFORMACION', 'Información'), ('ESTRUCTURA_ORGANIZACION', 'Estructura de la organización'), ('RED', 'Red')], max_length=25, verbose_name='Clase de Activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='custodio',
            field=models.CharField(blank=True, max_length=250, verbose_name='Custodio del Activo de Información'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='propietario',
            field=models.CharField(max_length=250, verbose_name='Propietario del activo'),
        ),
    ]
