# Generated by Django 6.1 on 2026-08-25 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0007_alter_activo_clase_activo_alter_activo_custodio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, db_column='actualizadoEn'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='clase_activo',
            field=models.CharField(choices=[('SISTEMAS_INFORMACION', 'Sistemas de Información'), ('PERSONAL', 'Personal'), ('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('INFORMACION', 'Información'), ('ESTRUCTURA_ORGANIZACION', 'Estructura de la organización'), ('RED', 'Red')], db_column='claseActivo', max_length=25, verbose_name='Clase de Activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='contiene_datos_personales',
            field=models.BooleanField(db_column='contieneDatosPersonales', default=False, verbose_name='¿El activo contiene datos personales (Ley 1581 de 2012)? LEY DATOS PERSONALES'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='direccion',
            field=models.ForeignKey(db_column='direccionId', on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.direccion', verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='fecha_baja',
            field=models.DateField(blank=True, db_column='fechaBaja', null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='tipo_activo',
            field=models.CharField(choices=[('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario')], db_column='tipoActivo', max_length=15, verbose_name='Tipo de Activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='valor_confidencialidad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], db_column='valorConfidencialidad', default='MEDIA', max_length=5, verbose_name='Confidencialidad'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='valor_disponibilidad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], db_column='valorDisponibilidad', default='MEDIA', max_length=5, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='valor_integridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], db_column='valorIntegridad', default='MEDIA', max_length=5, verbose_name='Integridad'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, db_column='actualizadoEn'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='proceso',
            field=models.ForeignKey(blank=True, db_column='procesoId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to='activos.proceso', verbose_name='Proceso'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, db_column='actualizadoEn'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterModelTable(
            name='activo',
            table='activo',
        ),
        migrations.AlterModelTable(
            name='direccion',
            table='direccion',
        ),
        migrations.AlterModelTable(
            name='proceso',
            table='proceso',
        ),
    ]
