# Generated by Django 6.1 on 2026-09-21 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0010_seed_procesos_hallazgos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionSemestralActivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('periodo', models.CharField(max_length=20, unique=True, verbose_name='Periodo')),
                ('fecha_revision', models.DateField(db_column='fechaRevision', default=django.utils.timezone.localdate, verbose_name='Fecha de revisión')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('realizada_por', models.ForeignKey(blank=True, db_column='realizadaPorId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_activos', to=settings.AUTH_USER_MODEL, verbose_name='Realizada por')),
            ],
            options={
                'verbose_name': 'revisión semestral de activos',
                'verbose_name_plural': 'revisiones semestrales de activos',
                'db_table': 'revisionSemestralActivos',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Activo de Información')),
                ('proceso_nombre', models.CharField(blank=True, db_column='procesoNombre', max_length=150, null=True, verbose_name='Proceso')),
                ('direccion_nombre', models.CharField(db_column='direccionNombre', max_length=150, verbose_name='Dirección')),
                ('tipo_activo', models.CharField(choices=[('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario')], db_column='tipoActivo', max_length=15)),
                ('clase_activo', models.CharField(choices=[('SISTEMAS_INFORMACION', 'Sistemas de Información'), ('PERSONAL', 'Personal'), ('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('INFORMACION', 'Información'), ('ESTRUCTURA_ORGANIZACION', 'Estructura de la organización'), ('RED', 'Red')], db_column='claseActivo', max_length=25)),
                ('naturaleza', models.CharField(choices=[('FISICO', 'Fisico'), ('DIGITAL', 'Digital'), ('SAAS', 'SaaS'), ('IAAS', 'IaaS'), ('PAAS', 'PaaS')], max_length=15)),
                ('propietario', models.CharField(max_length=250)),
                ('custodio', models.CharField(blank=True, max_length=250)),
                ('etiquetado', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('CONFIDENCIAL', 'Confidencial')], max_length=15)),
                ('contiene_datos_personales', models.BooleanField(db_column='contieneDatosPersonales', default=False)),
                ('valor_confidencialidad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], db_column='valorConfidencialidad', max_length=5)),
                ('valor_integridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], db_column='valorIntegridad', max_length=5)),
                ('valor_disponibilidad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], db_column='valorDisponibilidad', max_length=5)),
                ('puntaje_valoracion', models.PositiveSmallIntegerField(db_column='puntajeValoracion')),
                ('criticidad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=5)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('RETIRADO', 'Retirado')], max_length=20)),
                ('activo_original', models.ForeignKey(blank=True, db_column='activoOriginalId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='activos.activo')),
                ('revision', models.ForeignKey(db_column='revisionId', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='activos.revisionsemestralactivos')),
            ],
            options={
                'verbose_name': 'foto de activo',
                'verbose_name_plural': 'fotos de activos',
                'db_table': 'snapshotActivo',
                'ordering': ['codigo'],
            },
        ),
    ]
