# Generated by Django 6.1 on 2026-08-13 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='otp_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='otp_secreto',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='CodigoRecuperacionOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(max_length=128)),
                ('usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacion_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'código de recuperación OTP',
                'verbose_name_plural': 'códigos de recuperación OTP',
            },
        ),
    ]
