# Generated by Django 6.1 on 2026-08-14 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_otp_habilitado_usuario_otp_secreto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='otp_metodo',
            field=models.CharField(choices=[('APP', 'Aplicación de autenticación'), ('EMAIL', 'Correo electrónico')], default='APP', max_length=10),
        ),
        migrations.CreateModel(
            name='CodigoOtpCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(max_length=128)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_otp_correo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'código OTP por correo',
                'verbose_name_plural': 'códigos OTP por correo',
                'ordering': ['-creado_en'],
            },
        ),
    ]
