# Generated by Django 6.1 on 2026-08-20 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_otp_metodo_codigootpcorreo'),
        ('activos', '0007_alter_activo_clase_activo_alter_activo_custodio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='area',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='activos.direccion', verbose_name='Dirección'),
        ),
    ]
