# Generated by Django 6.1 on 2026-08-25 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_usuario_area_usuario_direccion'),
        ('activos', '0008_camel_case_db'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='email_intentado',
            field=models.EmailField(blank=True, db_column='emailIntentado', max_length=254),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_column='ipAddress', null=True),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='tipo_evento',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FALLIDO', 'Intento fallido')], db_column='tipoEvento', max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='user_agent',
            field=models.CharField(blank=True, db_column='userAgent', max_length=300),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bitacoraaccion',
            name='content_type',
            field=models.ForeignKey(db_column='contentTypeId', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='bitacoraaccion',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_column='ipAddress', null=True),
        ),
        migrations.AlterField(
            model_name='bitacoraaccion',
            name='object_id',
            field=models.CharField(db_column='objectId', max_length=64),
        ),
        migrations.AlterField(
            model_name='bitacoraaccion',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codigootpcorreo',
            name='codigo_hash',
            field=models.CharField(db_column='codigoHash', max_length=128),
        ),
        migrations.AlterField(
            model_name='codigootpcorreo',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterField(
            model_name='codigootpcorreo',
            name='expira_en',
            field=models.DateTimeField(db_column='expiraEn'),
        ),
        migrations.AlterField(
            model_name='codigootpcorreo',
            name='usuario',
            field=models.ForeignKey(db_column='usuarioId', on_delete=django.db.models.deletion.CASCADE, related_name='codigos_otp_correo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codigorecuperacionotp',
            name='codigo_hash',
            field=models.CharField(db_column='codigoHash', max_length=128),
        ),
        migrations.AlterField(
            model_name='codigorecuperacionotp',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterField(
            model_name='codigorecuperacionotp',
            name='usado_en',
            field=models.DateTimeField(blank=True, db_column='usadoEn', null=True),
        ),
        migrations.AlterField(
            model_name='codigorecuperacionotp',
            name='usuario',
            field=models.ForeignKey(db_column='usuarioId', on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacion_otp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rol',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, db_column='actualizadoEn'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='es_rol_sistema',
            field=models.BooleanField(db_column='esRolSistema', default=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='grupo',
            field=models.OneToOneField(db_column='grupoId', on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(db_column='debeCambiarPassword', default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.ForeignKey(blank=True, db_column='direccionId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='activos.direccion', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(db_column='nombreCompleto', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='otp_habilitado',
            field=models.BooleanField(db_column='otpHabilitado', default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='otp_metodo',
            field=models.CharField(choices=[('APP', 'Aplicación de autenticación'), ('EMAIL', 'Correo electrónico')], db_column='otpMetodo', default='APP', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='otp_secreto',
            field=models.CharField(blank=True, db_column='otpSecreto', max_length=32),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='asignado_por',
            field=models.ForeignKey(blank=True, db_column='asignadoPorId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, db_column='fechaAsignacion'),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='rol',
            field=models.ForeignKey(db_column='rolId', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to='accounts.rol'),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(db_column='usuarioId', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='bitacoraacceso',
            table='bitacoraAcceso',
        ),
        migrations.AlterModelTable(
            name='bitacoraaccion',
            table='bitacoraAccion',
        ),
        migrations.AlterModelTable(
            name='codigootpcorreo',
            table='codigoOtpCorreo',
        ),
        migrations.AlterModelTable(
            name='codigorecuperacionotp',
            table='codigoRecuperacionOtp',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        migrations.AlterModelTable(
            name='usuariorol',
            table='usuarioRol',
        ),
    ]
