# Generated by Django 6.1 on 2026-08-28 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_camel_case_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperacionPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(db_column='codigoHash', max_length=128)),
                ('expira_en', models.DateTimeField(db_column='expiraEn')),
                ('usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('usuario', models.ForeignKey(db_column='usuarioId', on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacion_password', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'código de recuperación de contraseña',
                'verbose_name_plural': 'códigos de recuperación de contraseña',
                'db_table': 'codigoRecuperacionPassword',
                'ordering': ['-creado_en'],
            },
        ),
    ]
