# Generated by Django 6.1 on 2026-09-22 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_codigorecuperacionpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('nombre_completo', models.CharField(db_column='nombreCompleto', max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo en la organización?')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'db_table': 'empleado',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='empleado',
            field=models.OneToOneField(blank=True, db_column='empleadoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='accounts.empleado', verbose_name='Empleado asociado'),
        ),
    ]
