# Generated by Django 6.1 on 2026-08-13 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('POLITICA', 'Política'), ('PROCEDIMIENTO', 'Procedimiento'), ('MANUAL', 'Manual'), ('FORMATO', 'Formato'), ('REGISTRO', 'Registro'), ('INSTRUCTIVO', 'Instructivo')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('version_actual', models.CharField(default='1.0', max_length=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('VIGENTE', 'Vigente'), ('OBSOLETO', 'Obsoleto')], default='BORRADOR', max_length=15)),
                ('archivo', models.FileField(blank=True, upload_to='documentos/%Y/%m/')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_proxima_revision', models.DateField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_propios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=10)),
                ('cambios', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, upload_to='documentos/versiones/%Y/%m/')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_documento_creadas', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='documentos.documento')),
            ],
            options={
                'verbose_name': 'versión de documento',
                'verbose_name_plural': 'versiones de documento',
                'ordering': ['-creado_en'],
                'unique_together': {('documento', 'version')},
            },
        ),
    ]
