# Generated by Django 6.1 on 2026-08-25 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, db_column='actualizadoEn'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, db_column='aprobadoPorId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, db_column='fechaAprobacion', null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_proxima_revision',
            field=models.DateField(blank=True, db_column='fechaProximaRevision', null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='propietario',
            field=models.ForeignKey(db_column='propietarioId', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_propios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='version_actual',
            field=models.CharField(db_column='versionActual', default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='versiondocumento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, db_column='actualizadoEn'),
        ),
        migrations.AlterField(
            model_name='versiondocumento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterField(
            model_name='versiondocumento',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='creadoPorId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_documento_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='versiondocumento',
            name='documento',
            field=models.ForeignKey(db_column='documentoId', on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='documentos.documento'),
        ),
        migrations.AlterModelTable(
            name='documento',
            table='documento',
        ),
        migrations.AlterModelTable(
            name='versiondocumento',
            table='versionDocumento',
        ),
    ]
