# Generated by Django 6.1 on 2026-08-26 20:41

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_camel_case_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, upload_to='documentos/%Y/%m/', validators=[apps.core.validators.validar_extension_archivo, apps.core.validators.validar_tamano_archivo]),
        ),
        migrations.AlterField(
            model_name='versiondocumento',
            name='archivo',
            field=models.FileField(blank=True, upload_to='documentos/versiones/%Y/%m/', validators=[apps.core.validators.validar_extension_archivo, apps.core.validators.validar_tamano_archivo]),
        ),
    ]
