# Generated by Django 6.1 on 2026-08-28 20:18

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_documento_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, upload_to='documentos/%Y/%m/', validators=[apps.core.validators.validar_extension_archivo, apps.core.validators.validar_tamano_archivo]),
        ),
        migrations.AlterField(
            model_name='versiondocumento',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, upload_to='documentos/versiones/%Y/%m/', validators=[apps.core.validators.validar_extension_archivo, apps.core.validators.validar_tamano_archivo]),
        ),
    ]
