# Generated by Django 6.1 on 2026-09-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documento_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('POLITICA', 'Política'), ('PROCEDIMIENTO', 'Procedimiento'), ('MANUAL', 'Manual'), ('FORMATO', 'Formato'), ('REGISTRO', 'Registro'), ('INSTRUCTIVO', 'Instructivo'), ('PLAN', 'Plan')], max_length=20),
        ),
    ]
