# Generated by Django 6.1 on 2026-09-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_alter_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('POLITICA', 'Política'), ('PROCEDIMIENTO', 'Procedimiento'), ('MANUAL', 'Manual'), ('FORMATO', 'Formato'), ('REGISTRO', 'Registro'), ('INSTRUCTIVO', 'Instructivo'), ('PLAN', 'Plan'), ('MATRIZ', 'Matriz'), ('GUIA', 'Guía'), ('PROGRAMA', 'Programa'), ('PROTOCOLO', 'Protocolo')], max_length=20),
        ),
    ]
