# Generated by Django 6.1 on 2026-09-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_alter_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('FORMATO', 'Formato'), ('GUIA', 'Guía'), ('INSTRUCTIVO', 'Instructivo'), ('MANUAL', 'Manual'), ('MATRIZ', 'Matriz'), ('PLAN', 'Plan'), ('POLITICA', 'Política'), ('PROCEDIMIENTO', 'Procedimiento'), ('PROGRAMA', 'Programa'), ('PROTOCOLO', 'Protocolo'), ('REGISTRO', 'Registro')], max_length=20),
        ),
    ]
