# Generated by Django 6.1 on 2026-09-11 20:18

import apps.core.validators
import apps.documentos.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_alter_documento_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versiondocumento',
            options={'ordering': ['-fecha_version', '-creado_en'], 'verbose_name': 'versión de documento', 'verbose_name_plural': 'versiones de documento'},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='versiondocumento',
            name='fecha_version',
            field=models.DateField(db_column='fechaVersion', default=django.utils.timezone.localdate, verbose_name='Fecha de la versión'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.documentos.models.ruta_archivo_documento, validators=[apps.core.validators.validar_extension_archivo, apps.core.validators.validar_tamano_archivo]),
        ),
        migrations.AlterField(
            model_name='versiondocumento',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.documentos.models.ruta_archivo_version_documento, validators=[apps.core.validators.validar_extension_archivo, apps.core.validators.validar_tamano_archivo]),
        ),
        migrations.AlterField(
            model_name='versiondocumento',
            name='cambios',
            field=models.TextField(blank=True, verbose_name='Descripción del cambio'),
        ),
        migrations.AlterField(
            model_name='versiondocumento',
            name='version',
            field=models.CharField(max_length=10, verbose_name='Versión'),
        ),
    ]
