# Generated by Django 6.1 on 2026-08-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='ID Indicador')),
                ('tipo', models.CharField(choices=[('EFICACIA', 'Eficacia'), ('CULTURA_RESULTADO', 'Cultura / Resultado'), ('PREVENTIVO_OPERATIVO', 'Preventivo / Operativo'), ('CONTINUIDAD_OPERATIVO', 'Continuidad / Operativo')], max_length=25, verbose_name='Tipo de indicador')),
                ('nombre', models.CharField(max_length=200)),
                ('objetivo', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=150, verbose_name='Unidad de medida del indicador')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('formula', models.TextField(blank=True, verbose_name='Fórmula')),
                ('frecuencia', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=15)),
                ('responsable_medicion', models.CharField(blank=True, max_length=200, verbose_name='Responsable de la medición')),
                ('correo_propietario', models.CharField(blank=True, max_length=300, verbose_name='Correo propietario')),
                ('meta', models.CharField(blank=True, max_length=100)),
                ('fuente_datos', models.TextField(blank=True, verbose_name='Fuente de datos')),
                ('responsable_analisis', models.CharField(blank=True, max_length=200, verbose_name='Responsable del análisis')),
                ('analisis', models.TextField(blank=True, verbose_name='Análisis')),
                ('accion', models.TextField(blank=True, verbose_name='Acción')),
            ],
            options={
                'verbose_name': 'indicador',
                'verbose_name_plural': 'indicadores',
                'ordering': ['codigo'],
            },
        ),
    ]
