# Generated by Django 6.1 on 2026-08-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(max_length=50, verbose_name='Periodo')),
                ('fecha_cargue', models.DateField(verbose_name='Fecha de cargue')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('archivo_soporte', models.FileField(blank=True, upload_to='indicadores/seguimientos/%Y/%m/', verbose_name='Archivo soporte')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='indicadores.indicador')),
            ],
            options={
                'verbose_name': 'seguimiento de indicador',
                'verbose_name_plural': 'seguimientos de indicador',
                'ordering': ['-fecha_cargue'],
            },
        ),
    ]
