# Generated by Django 6.1 on 2026-08-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_seguimiento_indicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoindicador',
            name='resultado',
            field=models.FloatField(blank=True, null=True, verbose_name='Resultado (según fórmula del indicador)'),
        ),
    ]
