# Generated by Django 6.1 on 2026-08-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_resultado_y_cumplimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoindicador',
            name='denominador',
            field=models.FloatField(blank=True, null=True, verbose_name='Denominador'),
        ),
        migrations.AddField(
            model_name='seguimientoindicador',
            name='numerador',
            field=models.FloatField(blank=True, null=True, verbose_name='Numerador'),
        ),
    ]
