# Generated by Django 6.1 on 2026-08-25 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0004_numerador_denominador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, db_column='actualizadoEn'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='correo_propietario',
            field=models.CharField(blank=True, db_column='correoPropietario', max_length=300, verbose_name='Correo propietario'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='fuente_datos',
            field=models.TextField(blank=True, db_column='fuenteDatos', verbose_name='Fuente de datos'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='responsable_analisis',
            field=models.CharField(blank=True, db_column='responsableAnalisis', max_length=200, verbose_name='Responsable del análisis'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='responsable_medicion',
            field=models.CharField(blank=True, db_column='responsableMedicion', max_length=200, verbose_name='Responsable de la medición'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='unidad_medida',
            field=models.CharField(blank=True, db_column='unidadMedida', max_length=150, verbose_name='Unidad de medida del indicador'),
        ),
        migrations.AlterField(
            model_name='seguimientoindicador',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, db_column='actualizadoEn'),
        ),
        migrations.AlterField(
            model_name='seguimientoindicador',
            name='archivo_soporte',
            field=models.FileField(blank=True, db_column='archivoSoporte', upload_to='indicadores/seguimientos/%Y/%m/', verbose_name='Archivo soporte'),
        ),
        migrations.AlterField(
            model_name='seguimientoindicador',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_column='creadoEn'),
        ),
        migrations.AlterField(
            model_name='seguimientoindicador',
            name='fecha_cargue',
            field=models.DateField(db_column='fechaCargue', verbose_name='Fecha de cargue'),
        ),
        migrations.AlterField(
            model_name='seguimientoindicador',
            name='indicador',
            field=models.ForeignKey(db_column='indicadorId', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='indicadores.indicador'),
        ),
        migrations.AlterModelTable(
            name='indicador',
            table='indicador',
        ),
        migrations.AlterModelTable(
            name='seguimientoindicador',
            table='seguimientoIndicador',
        ),
    ]
