# Generated by Django 6.1 on 2026-08-28 21:03

import apps.core.validators
import apps.indicadores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0007_alter_seguimientoindicador_archivo_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientoindicador',
            name='archivo_soporte',
            field=models.FileField(blank=True, db_column='archivoSoporte', max_length=255, upload_to=apps.indicadores.models.ruta_soporte_seguimiento, validators=[apps.core.validators.validar_extension_archivo, apps.core.validators.validar_tamano_archivo], verbose_name='Archivo soporte'),
        ),
    ]
